/** Word-level IPA overrides for Arabic. */
export const ar: Record<string, string> = {
  أحدا: '/ʔaˈħadan/', // anyone
  أحدهما: '/ʔaħaduˈhumaː/', // one of them two
  أحرارا: '/ʔaħˈraːran/',
  أسخيليوس: '/ʔasxiːˈliːjuːs/', // Aeschylus
  أمهات: '/umːaˈhaːt/',
  أنسيت: '/ʔunˈsiːt/',
  أنعمت: '/ʔanˈʕamta/',
  أورفليس: '/ʔurˈfaliːs/', // Orphalese (Gibran)
  أيديهم: '/ʔajˈdiːhim/',
  استيقظت: '/istajˈqaðˤtu/',
  اسمه: '/ˈismuhu/', // his name
  اعتزاله: '/iʕtiˈzaːlihi/', // his seclusion
  الأليفة: '/alʔaˈliːfah/',
  الحياة: '/alħaˈjaːh/',
  الخليفة: '/alxaˈliːfah/',
  الذكريات: '/aðːikraˈjaːt/',
  السماوات: '/asːamaːˈwaːt/',
  الضالين: '/adˤːaːˈliːn/',
  العالمين: '/alʕaːlaˈmiːn/',
  العشرة: '/alˈʕaʃara/', // the ten
  الغربة: '/alˈɣurbah/',
  الغزاة: '/alɣuˈzaːh/',
  الكرامة: '/alkaˈraːmah/',
  اللوى: '/alˈliwaː/',
  المصطفى: '/almusˈtˤafaː/',
  امرأة: '/imˈraʔah/',
  اهدنا: '/ihˈdinaː/',
  بأوقافه: '/biʔawˈqaːfihi/', // with his endowments
  بإذنه: '/biʔiðˈnihi/',
  بجزائر: '/bidʒaˈzaːʔir/', // with islands
  بداية: '/biˈdaːjah/',
  بذي: '/biˈðiː/', // of importance
  بشيء: '/biˈʃajʔ/',
  بعضا: '/ˈbaʕdˤan/',
  بعضهم: '/baʕˈdˤuhum/',
  بعينه: '/biˈʕajnihi/',
  بعينيها: '/biʕajˈnajhaː/',
  بيدبا: '/bajdaˈbaː/', // Bidpai
  تأخذه: '/taʔˈxuðuhu/',
  تسقني: '/tasˈqiniː/',
  تعلمت: '/taʕalːˈamtu/',
  تقفن: '/taqifˈna/',
  جلست: '/dʒaˈlasat/',
  حارتنا: '/ħaːˈratnaː/',
  حفظهما: '/ħifˈðˤahumaː/',
  حكاية: '/ħiˈkaːjah/',
  حياته: '/ħaˈjaːtahu/',
  خفيفا: '/xaˈfiːfan/',
  خلالها: '/xiˈlaːlahaː/',
  خلفهم: '/xalˈfahum/',
  خمرا: '/ˈxamran/',
  دبشليم: '/dabʃaˈliːm/', // King Dabshelim
  رائحة: '/ˈraːʔiħah/',
  رافعا: '/ˈraːfiʕan/',
  رسمها: '/rasˈmuhaː/',
  رياحك: '/riˈjaːħaka/',
  زعموا: '/zaˈʕamuː/',
  زمانه: '/zaˈmaːnihi/',
  سادتي: '/saːˈdatiː/',
  ساسان: '/saːˈsaːn/', // Sasanian dynasty
  سبعة: '/ˈsabʕah/',
  ستحمله: '/sataħˈmiluhu/',
  سفينته: '/saˈfiːnatuhu/',
  سكرة: '/ˈsakrah/',
  سنة: '/ˈsanah/',
  سنين: '/siˈniːn/',
  شهريار: '/ʃahriˈjaːr/', // King Shahryar (1001 Nights)
  شيئا: '/ˈʃajʔan/',
  صغارها: '/sˤiˈɣaːruhaː/',
  طالعا: '/ˈtˤaːliʕan/',
  طويلة: '/tˤaˈwiːlah/',
  عاما: '/ˈʕaːman/',
  عجيبة: '/ʕaˈdʒiːbah/',
  عدت: '/ˈʕudtu/',
  عصره: '/ˈʕasˤrihi/',
  علمه: '/ˈʕilmihi/',
  عليك: '/ʕaˈlajka/',
  عليهم: '/ʕaˈlajhim/',
  عنده: '/ˈʕindahu/',
  عنها: '/ʕanˈhaː/', // about it
  غيبة: '/ˈɣajbah/',
  فإن: '/faˈʔin/',
  فاسقني: '/fasˈqiniː/',
  فاغتنمها: '/faɣˈtanimhaː/',
  فالمقراة: '/falˈmiqraːh/',
  فجرا: '/ˈfadʒran/',
  فحومل: '/faˈħawmal/',
  فما: '/faˈmaː/',
  فيه: '/fiːhi/',
  فيها: '/ˈfiːhaː/',
  قالت: '/ˈqaːlat/',
  قصة: '/ˈqisˤːah/',
  قلت: '/ˈqultu/', // I said
  كتابات: '/kitaːˈbaːt/',
  كرسيه: '/kurˈsijːuhu/',
  لوهلة: '/liˈwahlah/',
  مبنية: '/mabˈnijːah/',
  متقطعا: '/mutaqatˤˈtˤiʕan/',
  مدينة: '/maˈdiːnah/',
  مهيار: '/mahˈjaːr/', // Mahyar (Adonis)
  ميلاده: '/miːˈlaːdihi/',
  نسجتها: '/nasaˈdʒathaː/',
  نوما: '/ˈnawman/',
  هادما: '/ˈhaːdiman/',
  هوذا: '/haːˈðaː/',
  وأعوان: '/waʔaʕˈwaːn/', // and followers
  وإنما: '/waʔinːaˈmaː/',
  وإياك: '/waʔijˈjaːka/',
  والسنة: '/wasːˈanah/',
  والقال: '/walˈqaːl/', // and the talk
  والمحبة: '/walmaˈħabːah/',
  وبشروطه: '/wabiʃuˈruːtihi/', // and his conditions
  وحكايات: '/waħikaːˈjaːt/',
  وشمأل: '/waʃaˈmaʔl/',
  وضعه: '/ˈwadˤʕihi/',
  وعليهم: '/waʕaˈlajhim/',
  وغاب: '/waˈɣaːb/',
  وفطنة: '/waˈfitˤnah/',
  وما: '/waˈmaː/',
  ومتساوين: '/wamutasaːˈwiːn/',
  ومنزل: '/waˈmanzil/',
  وهبوا: '/wuˈhibuː/',
  يؤوده: '/jaʔuːˈduhu/',
  يتخطى: '/jataˈxatˤːaː/',
  يحيطون: '/juħiːˈtˤuːn/',
  يضعه: '/jadˤaˈʕuhu/',
  يعاملوا: '/juˈʕaːmiluː/',
  يهتموا: '/jahtamˈmuː/', // they cared
};
