/** Esperanto IPA overrides for words not in the dictionary. */
export const eo: Record<string, string> = {
  adiaŭluma: 'adiawluma',
  aŭdeblaj: 'awdeblaj',
  briletas: 'briletas',
  doma: 'doma',
  donadis: 'donadis',
  duona: 'duona',
  elspezadis: 'elspezadis',
  Fortego: 'forteɡo',
  grimpadis: 'grimpadis',
  hejto: 'hejto',
  hor: 'hor',
  horizont: 'horizont',
  kor: 'kor',
  l: 'l',
  Mefisto: 'mefisto',
  mond: 'mond',
  Netuŝebla: 'netuʃebla',
  nokta: 'nokta',
  noktaj: 'noktaj',
  okul: 'okul',
  or: 'or',
  palas: 'palas',
  plorbruluma: 'plorbruluma',
  resultaton: 'resultaton',
  sang: 'sanɡ',
  seĝetoj: 'sedʒetoj',
  sendignigan: 'sendignigan',
  sklavkomerco: 'sklavkomertso',
  sun: 'sun',
  tagmeza: 'taɡmeza',
  traboras: 'traboras',
  traportos: 'traportos',
  voj: 'voj',
  zorgadis: 'zorɡadis',
};
