/** Word-level IPA overrides for Finnish. */
export const fi: Record<string, string> = {
  // Finnish is nearly perfectly phonetic, so most IPA can be derived from spelling.
  // These overrides cover inflected forms and proper nouns missing from the ipa-dict.

  // Inflected forms — verbs
  aaltoili: '/ˈɑːltoili/',
  // Proper nouns and place names
  abraham: '/ˈɑbrɑhɑm/',
  äijänrahjus: '/ˈæijænrɑhjus/',
  aliide: '/ˈɑliːde/',
  aliidea: '/ˈɑliːdeɑ/',
  alkavat: '/ˈɑlkɑʋɑt/',
  anna: '/ˈɑnːɑ/',
  benjaminpoika: '/ˈbenjɑminpoikɑ/',
  // Common function words
  en: '/en/',
  // Inflected forms — nominals (case + possessive)
  eräällä: '/ˈeræːlːæ/',
  erään: '/ˈeræːn/',
  eräänä: '/ˈeræːnæ/',
  esko: '/ˈesko/',
  eteläisessä: '/ˈetelæisesːæ/',
  hääretkelleni: '/ˈhæːretkelːeni/',
  hädässä: '/ˈhædæsːæ/',
  häipyvät: '/ˈhæipyʋæt/',
  hajoovat: '/ˈhɑjoːʋɑt/',

  hallaisella: '/ˈhɑlːɑiselːɑ/',
  hallatar: '/ˈhɑlːɑtɑr/',
  hämeessä: '/ˈhæmeːsːæ/',
  // Archaic Kalevala forms
  hampahilleni: '/ˈhɑmpɑhilːeni/',
  hänen: '/ˈhænen/',
  hehtaareja: '/ˈhehtɑːrejɑ/',
  heikompi: '/ˈheikompi/',
  heitä: '/ˈheitæ/',
  henkeni: '/ˈheŋkeni/',
  hetkehen: '/ˈhetkehen/',
  hiess: '/ˈhiesː/',
  // Abbreviated/dialectal forms
  "hiess'": '/ˈhiesː/',
  hietakankaalla: '/ˈhietɑkɑŋkɑːlːɑ/',
  // Additional words
  hiivin: '/ˈhiːʋin/',
  hoiti: '/ˈhoiti/',
  huokailen: '/ˈhuokɑilen/',
  hylkää: '/ˈhylkæː/',
  'iän-ikuinen': '/ˈiænikuinen/',
  ihmiset: '/ˈihmiset/',
  ilmarinen: '/ˈilmɑrinen/',
  iloitse: '/ˈiloitse/',
  impivaara: '/ˈimpiʋɑːrɑ/',
  itsensä: '/ˈitsensæ/',
  itsiäni: '/ˈitsiæni/',
  jäivät: '/ˈjæiʋæt/',
  jälkehen: '/ˈjælkehen/',
  jauhomyllyn: '/ˈjɑuhomylːyn/',
  johan: '/ˈjohɑn/',
  jokaisen: '/ˈjokɑisen/',
  jonka: '/ˈjoŋkɑ/',
  jossa: '/ˈjosːɑ/',
  juha: '/ˈjuhɑ/',
  jukolan: '/ˈjukolɑn/',

  jumalakin: '/ˈjumɑlɑkin/',
  jumalia: '/ˈjumɑliɑ/',
  jumaliin: '/ˈjumɑliːn/',
  kaada: '/ˈkɑːdɑ/',
  kärpästä: '/ˈkærpæstæ/',
  käskihän: '/ˈkæskihæn/',
  kaskisavu: '/ˈkɑskisɑʋu/',
  kaskisavuun: '/ˈkɑskisɑʋuːn/',
  käteen: '/ˈkæteːn/',
  kehittäminen: '/ˈkehitːæminen/',
  kemin: '/ˈkemin/',
  kerkiävät: '/ˈkerkiæʋæt/',
  kielelleni: '/ˈkielelːeni/',
  kipan: '/ˈkipɑn/',
  kirjoitan: '/ˈkirjoitɑn/',
  kirkonkirjojen: '/ˈkirkoŋkirjojen/',
  kolmantehen: '/ˈkolmɑntehen/',
  koskela: '/ˈkoskelɑ/',
  kuoleva: '/ˈkuoleʋɑ/',
  kuussa: '/ˈkuːsːɑ/',
  kylvi: '/ˈkylʋi/',
  kymmeniä: '/ˈkymːeniæ/',
  kynti: '/ˈkynti/',
  läheisin: '/ˈlæheisin/',
  lähell: '/ˈlæhelː/',
  "lähell'": '/ˈlæhelː/',
  laitahan: '/ˈlɑitɑhɑn/',
  lajivirsi: '/ˈlɑjiʋirsi/',
  lajivirttä: '/ˈlɑjiʋirtːæ/',
  lapsineen: '/ˈlɑpsineːn/',
  lastaan: '/ˈlɑstɑːn/',
  laulamahan: '/ˈlɑulɑmɑhɑn/',
  leipään: '/ˈleipæːn/',
  lensi: '/ˈlensi/',
  liisa: '/ˈliːsɑ/',

  lohduta: '/ˈlohdutɑ/',
  loista: '/ˈloistɑ/',
  lynnähyttelevi: '/ˈlynːæhytːeleʋi/',
  lyö: '/ˈlyø/',
  lyöä: '/ˈlyøæ/',
  // Compound/misc
  maamme: '/ˈmɑːmːe/',
  maataan: '/ˈmɑːtɑːn/',
  meidän: '/ˈmeidæn/',
  merelle: '/ˈmerelːe/',

  mieleni: '/ˈmieleni/',
  minun: '/ˈminun/',
  mulle: '/ˈmulːe/',
  muumilaakson: '/ˈmuːmilɑːkson/',
  muumipappa: '/ˈmuːmipɑpːɑ/',
  muumipeikko: '/ˈmuːmipeikːo/',
  muumitalon: '/ˈmuːmitɑlon/',
  niinkuin: '/ˈniːŋkuin/',
  niinpä: '/ˈniːnpæ/',
  nousi: '/ˈnousi/',
  ole: '/ˈole/',
  olen: '/ˈolen/',
  oli: '/ˈoli/',
  olivat: '/ˈoliʋɑt/',
  on: '/on/',
  paavo: '/ˈpɑːʋo/',
  palajaa: '/ˈpɑlɑjɑː/',
  pane: '/ˈpɑne/',
  perkas: '/ˈperkɑs/',
  pohjaisella: '/ˈpohjɑiselːɑ/',
  puettuna: '/ˈpuetːunɑ/',
  "puhe'et": '/ˈpuheːt/',
  pullottivat: '/ˈpulːotːiʋɑt/',
  putoelevat: '/ˈputoeleʋɑt/',
  rakkaampaa: '/ˈrɑkːɑːmpɑː/',
  rakkaampi: '/ˈrɑkːɑːmpi/',
  rauhaan: '/ˈrɑuhɑːn/',
  rinnassa: '/ˈrinːɑsːɑ/',
  rinteellä: '/ˈrinteːlːæ/',
  ruislinnun: '/ˈruislinːun/',
  saarijärven: '/ˈsɑːrijærʋen/',
  sammon: '/ˈsɑmːon/',
  sanelemahan: '/ˈsɑnelemɑhɑn/',
  seisoo: '/ˈseisoː/',
  senmutin: '/ˈsenmutin/',
  siivin: '/ˈsiːʋin/',
  sinisen: '/ˈsinisen/',
  sinuhe: '/ˈsinuhe/',
  sit: '/ˈsit/',
  "sit'": '/ˈsit/',
  soi: '/soi/',
  söi: '/ˈsøi/',
  sonnustan: '/ˈsonːustɑn/',
  sortuvin: '/ˈsortuʋin/',
  sukuvirsi: '/ˈsukuʋirsi/',
  sukuvirttä: '/ˈsukuʋirtːæ/',
  'sulhais-vaatteisin': '/ˈsulhɑisʋɑːtːeisin/',
  suolamyllyn: '/ˈsuolɑmylːyn/',
  suoltamahan: '/ˈsuoltɑmɑhɑn/',
  sure: '/ˈsure/',
  tähkäpäiden: '/ˈtæhkæpæiden/',
  taikuuri: '/ˈtɑikuːri/',
  taivaan: '/ˈtɑiʋɑːn/',
  tarttuin: '/ˈtɑrtːuin/',
  tartun: '/ˈtɑrtun/',
  tasalatvainen: '/ˈtɑsɑlɑtʋɑinen/',
  tekevi: '/ˈtekeʋi/',
  teräinen: '/ˈteræinen/',
  tiedetään: '/ˈtiedetæːn/',
  toisehen: '/ˈtoisehen/',
  toisensa: '/ˈtoisensɑ/',
  toivolan: '/ˈtoiʋolɑn/',
  toukola: '/ˈtoukolɑ/',
  toukolan: '/ˈtoukolɑn/',
  touon: '/ˈtouon/',
  truu: '/truː/',
  tuijotti: '/ˈtuijotːi/',

  tummuus: '/ˈtumːuːs/',
  tuntehin: '/ˈtuntehin/',
  tuntevat: '/ˈtunteʋɑt/',
  turms: '/turms/',
  vahvakaarnainen: '/ˈʋɑhʋɑkɑːrnɑinen/',
  vaikk: '/ˈʋɑikː/',
  "vaikk'": '/ˈʋɑikː/',
  vaimoineen: '/ˈʋɑimoineːn/',
  väinämöinen: '/ˈʋæinæmøinen/',
  vaivaamasta: '/ˈʋɑiʋɑːmɑstɑ/',
  valtiopäivä: '/ˈʋɑltiopæiʋæ/',

  valtoja: '/ˈʋɑltojɑ/',
  vastenmielisen: '/ˈʋɑstenmielisen/',
  veden: '/ˈʋeden/',
  veihän: '/ˈʋeihæn/',
  veljeään: '/ˈʋeljeæːn/',
  verhouu: '/ˈʋerhouː/',
  vettä: '/ˈʋetːæ/',
  ylistääkseni: '/ˈylistæːkseni/',

  zara: '/ˈtsɑrɑ/',
};
