/** Word-level IPA overrides for Icelandic. */
export const is: Record<string, string> = {
  ásir: '/ˈauːsɪr/',
  ásynjur: '/ˈauːsɪnjʏr/',
  ballir: '/ˈpatlɪr/',
  beytils: '/ˈpeiːtʰɪls/',
  Bjálfa: '/ˈpjaulva/',
  Bjarnar: '/ˈpjartnar/',
  blót: '/plouːtʰ/', // sacrifice/ritual
  bóklaus: '/ˈpoukʰlœys/',
  bréfberi: '/ˈprjɛːvpɛrɪ/', // letter carrier
  burlufóts: '/ˈpʏrtlʏfouts/',
  eflaði: '/ˈɛplaðɪ/', // past tense: strengthened/performed
  ek: '/ɛkʰ/',
  fannhvítir: '/ˈfanːkvitʰɪr/',
  farandi: '/ˈfarantɪ/',
  farsælda: '/ˈfarsailta/',
  fira: '/ˈfɪra/',
  flatnefur: '/ˈflatnɛvʏr/',
  flýðu: '/ˈfliːðʏ/',
  fornaldar: '/ˈfɔrtnaltar/',
  fornrit: '/ˈfɔrtnrɪtʰ/',
  frón: '/frouːn/',
  galdursmenn: '/ˈkaltʏrsmɛnː/',
  gautr: '/ˈkœyːtr/',
  hængs: '/ˈhaiŋs/',
  hagsælda: '/ˈhaksailta/',
  hálftrölls: '/ˈhaulftrœtls/',
  Hallbjarnar: '/ˈhatlpjartnar/',
  Hallfreðs: '/ˈhatlfrɛðs/', // genitive of Hallfreður
  Hallfreður: '/ˈhatlfrɛðʏr/', // proper name
  hárfagra: '/ˈhaurˌfaɣra/', // fair-haired (epithet)
  hersir: '/ˈhɛrsɪr/',
  hersis: '/ˈhɛrsɪs/',
  herskarar: '/ˈhɛrskʰarar/',
  Hrafnkelsdal: '/ˈr̥apnkʰɛlstalr/', // place name
  Hreggviðsson: '/ˈr̥ɛkːvɪðsːɔn/',
  hrímhvíta: '/ˈr̥imkvitʰa/',
  Ívarssonar: '/ˈivarsːɔnar/',
  jöklanna: '/ˈjœkʰlanːa/',
  Ketils: '/ˈkʰɛtʰɪls/',
  kindir: '/ˈkʰɪntɪr/',
  Kólumkilli: '/ˈkʰouːlʏmkʰɪtlɪ/',
  konungr: '/ˈkʰɔːnʏŋkr/',
  konungseigninni: '/ˈkʰɔːnʏŋkseiknɪnːɪ/',
  kotbóndi: '/ˈkʰɔtʰpountɪ/',
  kvongaður: '/ˈkʰvɔŋkaðʏr/',
  kynstór: '/ˈkʰɪnstouːr/',
  manndáðin: '/ˈmanːtauːðɪn/',
  mögu: '/ˈmœːkʏ/',
  nýu: '/ˈniːʏ/',
  óarga: '/ˈouːarka/',
  Önundur: '/ˈœːnʏntʏr/',
  öxn: '/ˈœksn/',
  plógsland: '/ˈpʰlouːkslant/',
  ráðu: '/ˈrauːðʏ/',
  rækir: '/ˈraiːkʰɪr/',
  Raumaríki: '/ˈrœyːmarɪːkʰɪ/',
  Raumsdælafylki: '/ˈrœymstailafɪlkʰɪ/',
  Raumsdal: '/ˈrœymstal/',
  Rein: '/reiːn/',
  söðul: '/ˈsœːðʏl/',
  sólkerfum: '/ˈsoulkʰɛrvʏm/',
  tindar: '/ˈtʰɪntar/',
  tívar: '/ˈtʰiːvar/',
  Valföðr: '/ˈvalvœðr/',
  Yngveldi: '/ˈɪŋkvɛltɪ/',
  þat: '/θatʰ/',
};
