/** Odia IPA overrides for words not in the dictionary. */

export const or_: Record<string, string> = {
  // Bande Utkala Janani (Odia anthem)
  ଅଙ୍ଗେ: 'ɔŋɡe',
  ଅପ୍ରମିତ: 'ɔpɾɔmit̪ɔ',
  ଆଗୁଁ: 'aːɡũ',
  ଆତ୍ମୀୟ: 'aːt̪miːjɔ',
  ଆରତ: 'aːɾɔt̪ɔ',
  ଉତ୍କଳଭୁବନେ: 'ut̪kɔl̪ɔbʱubɔne',
  ଉତ୍କଳର: 'ut̪kɔl̪ɔɾɔ',
  ଏ: 'e',
  // UDHR Article 1
  ଓ: 'o',
  ଔରସୁ: 'ɔwɾɔsu',
  କଳ: 'kɔl̪ɔ',
  କାତର: 'kaːt̪ɔɾɔ',
  କାରାଦଣ୍ଡେ: 'kaːɾaːd̪ɔɳɖe',
  କିମ୍ପା: 'kimpaː',
  କେବା: 'kebaː',
  // Madhusudan Das — Utkala Santana
  ଗଙ୍ଗା: 'ɡɔŋɡaː',
  ଗୋଦାବରୀ: 'ɡoːd̪aːbɔɾiː',
  ଚାରୁ: 't͡ʃaːɾu',
  ଚାଲିଯାଆନ୍ତୁ: 't͡ʃaːl̪ijaːaːnt̪u',
  ଜନ୍ମକାଳରୁ: 'd͡ʒɔnmɔkaːl̪ɔɾu',
  ତରଙ୍ଗେ: 't̪ɔɾɔŋɡe',
  ତୁହି: 't̪uhi',
  ତୋହର: 't̪oːhɔɾɔ',
  ଦୀର୍ଘିକା: 'd̪iːɾɡʱikaː',
  ଦୁଃଖ: 'd̪ukʱɔ',
  ଦେଶବାସୀ: 'd̪eʃɔbaːsiː',
  ଦେଶମାଟିରେ: 'd̪eʃɔmaːʈiɾe',
  ନର୍କେ: 'nɔɾke',
  ନିହିତ: 'nihit̪ɔ',
  ନୀଳାମ୍ବୁ: 'niːl̪aːmbu',
  ପଡ଼ିଥାଉ: 'pɔɖ̪it̪ʰaːu',
  ପରା: 'pɔɾaː',
  ପୂର୍ବପୁରୁଷ: 'puːɾbɔpuɾuʂɔ',
  ପୋଷଣ: 'poːʂɔɳɔ',
  ପ୍ରଜ୍ଞା: 'pɾɔd͡ʒɲaː',
  ପ୍ରାଣୀମାନଙ୍କ: 'pɾaːɳiːmaːnɔŋkɔ',
  ବନଭୂମି: 'bɔnɔbʱuːmi',
  ବନ୍ଦେ: 'bɔnd̪e',
  ବିବେକ: 'bibek',
  ବିଳାସ: 'bil̪aːsɔ',
  ବିହଙ୍ଗେ: 'bihɔŋɡe',
  ବୋଲାଉ: 'boːl̪aːu',
  ବ୍ୟଥା: 'bjɔt̪ʰaː',
  ଭଣ୍ଡାର: 'bʱɔɳɖaːɾɔ',
  ଭାତୃଭାବ: 'bʱaːt̪ɾubʱaːbɔ',
  ଭାଷମୟୀ: 'bʱaːʂɔmɔjiː',
  ଭୀରୁ: 'bʱiːɾu',
  ଭୂଧରମାଳା: 'bʱuːd̪ʱɔɾɔmaːl̪aː',
  ମରାଳମାଳିନୀ: 'mɔɾaːl̪ɔmaːl̪iniː',
  ମର୍ଯ୍ୟାଦା: 'mɔɾdʒjaːd̪aː',
  ମିଶୁ: 'miʃu',
  ମୁଖରିତ: 'mukʱɔɾit̪ɔ',
  ରାଜିତ: 'ɾaːd͡ʒit̪ɔ',
  ରୋଦନ: 'ɾoːd̪ɔnɔ',
  ଶୋଭାର: 'ʃobʱaːɾɔ',
  ସହୁ: 'sɔhu',
  ସାଜେ: 'saːd͡ʒe',
  ସେମାନଙ୍କଠାରେ: 'semaːnɔŋkɔʈʰaːɾe',
  ସୋଦର: 'soːd̪ɔɾɔ',
  ସ୍ୱାଧୀନ: 'swaːd̪ʱiːnɔ',
  ହାସମୟୀ: 'haːsɔmɔjiː',
  ହେଲ: 'hel̪ɔ',
};
