/** Word-level IPA overrides for Swahili. */
export const sw: Record<string, string> = {
  Asiyefunzwa: '/a.si.jɛ.ˈfu.nzwa/',
  dhulma: '/ˈðu.lma/',
  haimvunji: '/ha.i.m̩.ˈvu.ndʒi/',
  hakivunji: '/ha.ki.ˈvu.ndʒi/',
  Ibariki: '/i.ba.ˈri.ki/',
  ibariki: '/i.ba.ˈri.ki/',
  inayoonyesha: '/i.na.jɔ.ɔ.ˈɲɛ.ʃa/',
  isiyoibika: '/i.si.jɔ.i.ˈbi.ka/',
  kale: '/ˈka.lɛ/',
  kwanda: '/ˈkwa.nda/',
  mambo: '/ˈma.mbɔ/',
  mfanyabiashara: '/m̩.fa.ɲa.bi.a.ˈʃa.ra/',
  Mstahimilivu: '/m̩.sta.hi.mi.ˈli.vu/',
  sadiqi: '/sa.ˈdiː.ki/',
  uambiwalo: '/u.a.mbi.ˈwa.lɔ/',
  ujibane: '/u.dʒi.ˈba.nɛ/',
  ulithiqi: '/u.li.ˈθi.ki/',
  usiikhini: '/u.si.i.ˈxi.ni/',
  walioelimika: '/wa.li.ɔ.ɛ.li.ˈmi.ka/',
  watendeane: '/wa.tɛ.ndɛ.ˈa.nɛ/',
  yamenshika: '/ja.mɛ.n.ˈʃi.ka/',
  yanayoenda: '/ja.na.jɔ.ˈɛ.nda/',
  yatatulinda: '/ja.ta.tu.ˈli.nda/',
};
