/**
 * Downloads and parses the CMU Pronouncing Dictionary from GitHub.
 * Outputs a JSON file compatible with the existing dictionary format.
 *
 * Source: https://github.com/cmusphinx/cmudict
 *
 * Run with --force to re-download even if the file exists.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { execFile } from 'child_process';
import { promisify } from 'util';
import wordFrequencies from 'subtlex-word-frequencies';

const execFileAsync = promisify(execFile);

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Use .js extension to skip TypeScript transformation (88s -> <1s in vitest)
const OUTPUT_PATH = path.join(__dirname, '..', 'src', 'dictionary', 'cmudict.js');
const REVERSE_OUTPUT_PATH = path.join(__dirname, '..', 'src', 'dictionary', 'reverse-cmudict.js');
const WORD_FREQ_OUTPUT_PATH = path.join(__dirname, '..', 'src', 'data', 'word-frequencies.js');

const CMUDICT_URL = 'https://raw.githubusercontent.com/cmusphinx/cmudict/master/cmudict.dict';

interface CMUDictionary {
  [word: string]: string[];
}

async function downloadDictionary(): Promise<string> {
  console.log('Downloading CMU dictionary from GitHub...');

  try {
    // Use curl for reliable downloading (works in more environments than fetch/https)
    const { stdout } = await execFileAsync('curl', ['-sL', CMUDICT_URL], {
      maxBuffer: 10 * 1024 * 1024, // 10MB buffer
      encoding: 'utf8',
    });

    if (!stdout || stdout.length === 0) {
      throw new Error('Downloaded file is empty');
    }

    console.log(`Downloaded ${stdout.length} bytes`);
    return stdout;
  } catch (error) {
    throw new Error(
      `Failed to download using curl: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

function parseDictionary(text: string): CMUDictionary {
  console.log('Parsing dictionary...');
  const dict: CMUDictionary = {};
  const lines = text.split('\n');

  let parsed = 0;
  let skipped = 0;

  for (const line of lines) {
    // Skip empty lines and comments
    if (!line.trim() || line.startsWith(';;;')) {
      skipped++;
      continue;
    }

    // Format: WORD  PHONEMES or WORD(n)  PHONEMES
    // Single space separates word from phonemes in cmudict.dict
    const spaceIndex = line.indexOf(' ');
    if (spaceIndex > 0) {
      // Strip variant suffix e.g. AND(2) -> AND
      const rawWord = line.slice(0, spaceIndex);
      const word = rawWord.replace(/\(\d+\)$/, '');
      const phonemes = line.slice(spaceIndex + 1).trim();
      // Convert word to lowercase and pre-split phonemes into array
      // For variant pronunciations, only keep the first (most common)
      const key = word.toLowerCase();
      if (key in dict) {
        parsed++;
        continue;
      }
      dict[key] = phonemes.split(' ');
      parsed++;
    } else {
      skipped++;
    }
  }

  console.log(`Parsed: ${parsed}, Skipped: ${skipped}`);
  return dict;
}

async function fileExists(filepath: string): Promise<boolean> {
  try {
    await fs.access(filepath);
    return true;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  const forceUpdate = process.argv.includes('--force');

  // Check if all generated files exist
  const forwardExists = await fileExists(OUTPUT_PATH);
  const reverseExists = await fileExists(REVERSE_OUTPUT_PATH);

  // Skip if all dictionaries already exist (unless --force)
  if (!forceUpdate && forwardExists && reverseExists) {
    console.log('Dictionaries already exist, skipping download (use --force to re-download)');
    return;
  }

  let dict: CMUDictionary;
  const text = await downloadDictionary();
  dict = parseDictionary(text);

  const wordCount = Object.keys(dict).length;
  console.log(`Total entries: ${wordCount}`);

  // Use plain JS (not TS) to skip TypeScript transformation in vitest.
  // Phonemes are pre-split into arrays at build time to avoid runtime splitting.
  const jsContent = `// Auto-generated CMU dictionary - do not edit
// Generated by scripts/build-dictionary.ts
const cmudict = ${JSON.stringify(dict, null, 2)};
export default cmudict;
`;
  await fs.writeFile(OUTPUT_PATH, jsContent);
  console.log(`Written to ${OUTPUT_PATH}`);

  // Show file size
  const stats = await fs.stat(OUTPUT_PATH);
  console.log(`File size: ${(stats.size / 1024 / 1024).toFixed(2)} MB`);

  // Generate word-frequencies.ts from npm package
  await generateWordFrequencies();

  // Generate reverse dictionary (phoneme key -> words, sorted by frequency)
  await generateReverseDictionary(dict);
}

async function generateWordFrequencies(): Promise<void> {
  // Skip if already exists (unless --force)
  const forceUpdate = process.argv.includes('--force');
  if (!forceUpdate && (await fileExists(WORD_FREQ_OUTPUT_PATH))) {
    console.log('Word frequencies already exists, skipping (use --force to regenerate)');
    return;
  }

  // Ensure data directory exists
  await fs.mkdir(path.dirname(WORD_FREQ_OUTPUT_PATH), { recursive: true });

  // Convert array to object: { word: count }
  const frequencyMap: Record<string, number> = {};
  for (const { word, count } of wordFrequencies) {
    frequencyMap[word] = count;
  }

  const jsContent = `// Auto-generated word frequencies - do not edit
// Generated from subtlex-word-frequencies npm package
const WORD_FREQUENCIES = ${JSON.stringify(frequencyMap, null, 2)};
export default WORD_FREQUENCIES;
`;

  await fs.writeFile(WORD_FREQ_OUTPUT_PATH, jsContent);
  console.log(`Generated ${WORD_FREQ_OUTPUT_PATH}`);
  console.log(`Total words: ${Object.keys(frequencyMap).length}`);
}

/**
 * Strips stress markers (0, 1, 2) from the end of a phoneme.
 */
function stripStress(phoneme: string): string {
  const lastChar = phoneme.charCodeAt(phoneme.length - 1);
  // '0' = 48, '1' = 49, '2' = 50
  if (lastChar >= 48 && lastChar <= 50) {
    return phoneme.slice(0, -1);
  }
  return phoneme;
}

/**
 * Build word frequency map for sorting.
 */
function buildFrequencyMap(): Map<string, number> {
  const freqMap = new Map<string, number>();
  for (const { word, count } of wordFrequencies) {
    freqMap.set(word.toLowerCase(), count);
  }
  return freqMap;
}

// Common contractions that should be boosted in sorting
// (mirrors COMMON_CONTRACTIONS from utils/frequency.ts)
const COMMON_CONTRACTIONS = new Set([
  "can't",
  "won't",
  "don't",
  "didn't",
  "doesn't",
  "isn't",
  "aren't",
  "wasn't",
  "weren't",
  "hasn't",
  "haven't",
  "hadn't",
  "couldn't",
  "wouldn't",
  "shouldn't",
  "mustn't",
  "needn't",
  "mightn't",
  "shan't",
  "ain't",
  "i'll",
  "you'll",
  "he'll",
  "she'll",
  "it'll",
  "we'll",
  "they'll",
  "that'll",
  "who'll",
  "what'll",
  "there'll",
  "you're",
  "we're",
  "they're",
  "i've",
  "you've",
  "we've",
  "they've",
  "could've",
  "would've",
  "should've",
  "might've",
  "must've",
  "i'd",
  "you'd",
  "he'd",
  "she'd",
  "it'd",
  "we'd",
  "they'd",
  "that'd",
  "who'd",
  "he's",
  "she's",
  "it's",
  "that's",
  "what's",
  "who's",
  "where's",
  "there's",
  "here's",
  "how's",
  "let's",
  "i'm",
]);

const CONTRACTION_BOOST = 10_000_000;
const UNKNOWN_CONTRACTION_SCORE = 5_000_000;
const NUMERIC_REGEX = /[0-9]/;

/**
 * Score a word for sorting (higher = more common, should come first).
 * Mirrors scoreWord from utils/frequency.ts but inverted for descending sort.
 */
function getWordScore(word: string, freqMap: Map<string, number>): number {
  const freq = freqMap.get(word.toLowerCase()) ?? 0;
  const isContraction = COMMON_CONTRACTIONS.has(word.toLowerCase());

  if (freq > 0) {
    // Known words: use frequency, boost contractions
    return isContraction ? freq + CONTRACTION_BOOST : freq;
  }

  if (isContraction) {
    // Unknown contractions still get a high score
    return UNKNOWN_CONTRACTION_SCORE;
  }

  if (NUMERIC_REGEX.test(word)) {
    // Numeric words (like HELLO2) get very low score
    return -1_000_000 - word.length;
  }

  // Unknown words: negative score, shorter words slightly preferred
  return -word.length;
}

/**
 * Generates the reverse dictionary: phoneme key -> words (sorted by frequency).
 * Pre-built at build time to avoid runtime Map construction and sorting.
 */
async function generateReverseDictionary(dict: CMUDictionary): Promise<void> {
  console.log('Generating reverse dictionary...');

  const freqMap = buildFrequencyMap();

  // Build reverse mapping: phoneme key -> words
  const reverseDict: Record<string, string[]> = {};

  for (const [word, phonemes] of Object.entries(dict)) {
    // Strip stress markers and join to create key
    const phonemeKey = phonemes.map(stripStress).join(' ');

    if (!reverseDict[phonemeKey]) {
      reverseDict[phonemeKey] = [];
    }
    reverseDict[phonemeKey].push(word);
  }

  // Sort each word list by score (highest first = most common)
  for (const key of Object.keys(reverseDict)) {
    reverseDict[key].sort((a, b) => {
      return getWordScore(b, freqMap) - getWordScore(a, freqMap); // Descending
    });
  }

  const keyCount = Object.keys(reverseDict).length;
  console.log(`Reverse dictionary: ${keyCount} phoneme keys`);

  const jsContent = `// Auto-generated reverse CMU dictionary - do not edit
// Generated by scripts/build-dictionary.ts
// Maps phoneme sequences (stress-stripped) to words sorted by frequency
const reverseCmudict = ${JSON.stringify(reverseDict, null, 2)};
export default reverseCmudict;
`;

  await fs.writeFile(REVERSE_OUTPUT_PATH, jsContent);
  console.log(`Written to ${REVERSE_OUTPUT_PATH}`);

  const stats = await fs.stat(REVERSE_OUTPUT_PATH);
  console.log(`File size: ${(stats.size / 1024 / 1024).toFixed(2)} MB`);
}

main().catch(console.error);
