/**
 * Downloads and parses the CMU Pronouncing Dictionary from GitHub.
 * Outputs a JSON file compatible with the existing dictionary format.
 *
 * Source: https://github.com/cmusphinx/cmudict
 *
 * Run with --force to re-download even if the file exists.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';
import wordFrequencies from 'subtlex-word-frequencies';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = path.join(__dirname, '..', 'src', 'dictionary', 'cmudict.ts');
const WORD_FREQ_OUTPUT_PATH = path.join(__dirname, '..', 'src', 'data', 'word-frequencies.ts');

const CMUDICT_URL = 'https://raw.githubusercontent.com/cmusphinx/cmudict/master/cmudict.dict';

interface CMUDictionary {
  [word: string]: string;
}

async function downloadDictionary(): Promise<string> {
  console.log('Downloading CMU dictionary from GitHub...');
  const response = await fetch(CMUDICT_URL);
  if (!response.ok) {
    throw new Error(`Failed to download: ${response.status} ${response.statusText}`);
  }
  const text = await response.text();
  console.log(`Downloaded ${text.length} bytes`);
  return text;
}

// Minimal stub dictionary for sandboxed environments where download fails
const STUB_DICTIONARY: CMUDictionary = {
  hello: 'HH AH0 L OW1',
  world: 'W ER1 L D',
  the: 'DH AH0',
  a: 'AH0',
  is: 'IH1 Z',
  it: 'IH1 T',
  this: 'DH IH1 S',
  that: 'DH AE1 T',
  and: 'AE1 N D',
  or: 'AO1 R',
  test: 'T EH1 S T',
  example: 'IH0 G Z AE1 M P AH0 L',
};

function parseDictionary(text: string): CMUDictionary {
  console.log('Parsing dictionary...');
  const dict: CMUDictionary = {};
  const lines = text.split('\n');

  let parsed = 0;
  let skipped = 0;

  for (const line of lines) {
    // Skip empty lines and comments
    if (!line.trim() || line.startsWith(';;;')) {
      skipped++;
      continue;
    }

    // Format: WORD  PHONEMES or WORD(n)  PHONEMES
    // Single space separates word from phonemes in cmudict.dict
    const spaceIndex = line.indexOf(' ');
    if (spaceIndex > 0) {
      const word = line.slice(0, spaceIndex);
      const phonemes = line.slice(spaceIndex + 1).trim();
      // Convert word to lowercase to match npm package format
      dict[word.toLowerCase()] = phonemes;
      parsed++;
    } else {
      skipped++;
    }
  }

  console.log(`Parsed: ${parsed}, Skipped: ${skipped}`);
  return dict;
}

async function fileExists(filepath: string): Promise<boolean> {
  try {
    await fs.access(filepath);
    return true;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  const forceUpdate = process.argv.includes('--force');

  // Skip if dictionary already exists (unless --force)
  if (!forceUpdate && (await fileExists(OUTPUT_PATH))) {
    console.log('Dictionary already exists, skipping download (use --force to re-download)');
    return;
  }

  let dict: CMUDictionary;
  try {
    const text = await downloadDictionary();
    dict = parseDictionary(text);
  } catch (error) {
    console.warn('Failed to download dictionary:', error instanceof Error ? error.message : error);
    console.warn(
      'Using stub dictionary (limited functionality) - run with network access for full dictionary'
    );
    dict = STUB_DICTIONARY;
  }

  const wordCount = Object.keys(dict).length;
  console.log(`Total entries: ${wordCount}`);

  // IMPORTANT: Must use TypeScript with type annotation, NOT JSON!
  //
  // We tried JSON format for faster V8 parsing (JSON.parse is ~2x faster than
  // object literals), but bundlers (tsup/esbuild) convert JSON object keys
  // into individual variables for tree-shaking. This breaks because the
  // dictionary contains reserved words like "arguments", "eval", etc.
  //
  // The type annotation `Record<string, string>` tells the bundler to keep
  // the object structure intact instead of extracting keys as variables.
  const tsContent = `// Auto-generated CMU dictionary - do not edit
// Generated by scripts/build-dictionary.ts
const cmudict: Record<string, string> = ${JSON.stringify(dict, null, 2)};
export default cmudict;
`;
  await fs.writeFile(OUTPUT_PATH, tsContent);
  console.log(`Written to ${OUTPUT_PATH}`);

  // Show file size
  const stats = await fs.stat(OUTPUT_PATH);
  console.log(`File size: ${(stats.size / 1024 / 1024).toFixed(2)} MB`);

  // Generate word-frequencies.ts from npm package
  await generateWordFrequencies();
}

async function generateWordFrequencies(): Promise<void> {
  // Skip if already exists (unless --force)
  const forceUpdate = process.argv.includes('--force');
  if (!forceUpdate && (await fileExists(WORD_FREQ_OUTPUT_PATH))) {
    console.log('Word frequencies already exists, skipping (use --force to regenerate)');
    return;
  }

  // Ensure data directory exists
  await fs.mkdir(path.dirname(WORD_FREQ_OUTPUT_PATH), { recursive: true });

  // Convert array to object: { word: count }
  const frequencyMap: Record<string, number> = {};
  for (const { word, count } of wordFrequencies) {
    frequencyMap[word] = count;
  }

  const tsContent = `// Auto-generated word frequencies - do not edit
// Generated from subtlex-word-frequencies npm package
const WORD_FREQUENCIES: Record<string, number> = ${JSON.stringify(frequencyMap, null, 2)};
export default WORD_FREQUENCIES;
`;

  await fs.writeFile(WORD_FREQ_OUTPUT_PATH, tsContent);
  console.log(`Generated ${WORD_FREQ_OUTPUT_PATH}`);
  console.log(`Total words: ${Object.keys(frequencyMap).length}`);
}

main().catch(console.error);
