/**
 * Ingglish to ARPAbet converter.
 *
 * Used to parse Ingglish spellings back to ARPAbet phonemes
 * for reverse translation (Ingglish -> English).
 *
 * This is the reverse of arpabet-to-ingglish.ts.
 */

import { ARPABET_MAP } from './arpabet-to-ingglish';

/**
 * Mapping from Ingglish spellings to ARPAbet phonemes.
 * Generated by inverting the ARPABET_MAP.
 */
const INGGLISH_TO_ARPABET: Record<string, string> = {};
for (const [arpabet, ingglish] of Object.entries(ARPABET_MAP)) {
  INGGLISH_TO_ARPABET[ingglish] = arpabet;
}

/**
 * Spellings sorted by length (match longer patterns first).
 * For example, "sh" must be matched before "s".
 */
const SPELLINGS_BY_LENGTH = Object.keys(INGGLISH_TO_ARPABET).sort((a, b) => b.length - a.length);

/**
 * Converts an Ingglish spelling to ARPAbet phonemes.
 *
 * @param ingglish - Ingglish string (e.g., "hulo" for "hello")
 * @returns Array of ARPAbet phonemes (e.g., ["HH", "AH", "L", "OW"]), or null if empty
 */
export function ingglishToArpabet(ingglish: string): string[] | null {
  const result: string[] = [];
  let remaining = ingglish.toLowerCase();

  while (remaining.length > 0) {
    let matched = false;

    for (const spelling of SPELLINGS_BY_LENGTH) {
      if (remaining.startsWith(spelling)) {
        result.push(INGGLISH_TO_ARPABET[spelling]);
        remaining = remaining.slice(spelling.length);
        matched = true;
        break;
      }
    }

    if (!matched) {
      remaining = remaining.slice(1); // Skip unknown characters
    }
  }

  return result.length > 0 ? result : null;
}
