/**
 * Downloads and parses the CMU Pronouncing Dictionary from GitHub.
 * Outputs a JSON file compatible with the existing dictionary format.
 *
 * Source: https://github.com/cmusphinx/cmudict
 *
 * Run with --force to re-download even if the file exists.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { execFile } from 'child_process';
import { promisify } from 'util';
import wordFrequencies from 'subtlex-word-frequencies';
import { CUSTOM_PRONUNCIATIONS } from '../src/custom-words';
import { scoreWordWithFrequency } from '../src/frequency';

const execFileAsync = promisify(execFile);

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Use .js extension to skip TypeScript transformation (88s -> <1s in vitest)
const OUTPUT_PATH = path.join(__dirname, '..', 'src', 'cmudict.js');
const REVERSE_OUTPUT_PATH = path.join(__dirname, '..', 'src', 'reverse-cmudict.js');
const WORD_FREQ_OUTPUT_PATH = path.join(__dirname, '..', 'src', 'data', 'word-frequencies.js');
// en.json for the website (CMU dict + custom words merged)
const EN_JSON_PATH = path.join(__dirname, '..', '..', 'website', 'public', 'ipa-dicts', 'en.json');

const CMUDICT_URL = 'https://raw.githubusercontent.com/cmusphinx/cmudict/master/cmudict.dict';

interface CMUDictionary {
  [word: string]: string[];
}

async function downloadDictionary(): Promise<string> {
  console.log('Downloading CMU dictionary from GitHub...');

  try {
    // Use curl for reliable downloading (works in more environments than fetch/https)
    const { stdout } = await execFileAsync('curl', ['-sL', CMUDICT_URL], {
      maxBuffer: 10 * 1024 * 1024, // 10MB buffer
      encoding: 'utf8',
    });

    if (!stdout || stdout.length === 0) {
      throw new Error('Downloaded file is empty');
    }

    console.log(`Downloaded ${stdout.length} bytes`);
    return stdout;
  } catch (error) {
    throw new Error(
      `Failed to download using curl: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

export function parseDictionary(text: string): CMUDictionary {
  console.log('Parsing dictionary...');
  const dict: CMUDictionary = {};
  const lines = text.split('\n');

  let parsed = 0;
  let skipped = 0;

  for (const line of lines) {
    // Skip empty lines and comments
    if (!line.trim() || line.startsWith(';;;')) {
      skipped++;
      continue;
    }

    // Format: WORD  PHONEMES or WORD(n)  PHONEMES
    // Single space separates word from phonemes in cmudict.dict
    const spaceIndex = line.indexOf(' ');
    if (spaceIndex > 0) {
      // Strip variant suffix e.g. AND(2) -> AND
      const rawWord = line.slice(0, spaceIndex);
      const word = rawWord.replace(/\(\d+\)$/, '');
      // Strip inline "# ..." annotations (e.g. "AO1 L B ... # place, danish")
      // so comment tokens don't end up as fake phonemes.
      const rest = line.slice(spaceIndex + 1);
      const hashIndex = rest.indexOf('#');
      const phonemes = (hashIndex === -1 ? rest : rest.slice(0, hashIndex)).trim();
      // Convert word to lowercase and pre-split phonemes into array
      // For variant pronunciations, only keep the first (most common)
      const key = word.toLowerCase();
      if (key in dict) {
        parsed++;
        continue;
      }
      dict[key] = phonemes.split(' ');
      parsed++;
    } else {
      skipped++;
    }
  }

  console.log(`Parsed: ${parsed}, Skipped: ${skipped}`);

  // Pre-normalize velar nasals (N → NG before K/G) at build time
  // so the runtime loader doesn't need to scan every phoneme array.
  let normalized = 0;
  for (const phonemes of Object.values(dict)) {
    for (let i = 0; i < phonemes.length - 1; i++) {
      if (phonemes[i] === 'N' && (phonemes[i + 1] === 'K' || phonemes[i + 1] === 'G')) {
        phonemes[i] = 'NG';
        normalized++;
      }
    }
  }
  console.log(`Normalized ${normalized} velar nasals`);

  return dict;
}

/**
 * Writes both a .json file (for Node.js fast path) and a .js file
 * (with JSON.parse wrapper for Vite/browser).
 */
async function writeDualOutput(
  jsPath: string,
  data: object,
  varName: string,
  comment: string
): Promise<void> {
  const jsonContent = JSON.stringify(data);
  const jsonPath = jsPath.replace('.js', '.json');
  const jsContent = `// ${comment}
// Generated by scripts/build-dictionary.ts
const ${varName} = JSON.parse(\`${jsonContent}\`);
export default ${varName};
`;
  await Promise.all([fs.writeFile(jsonPath, jsonContent), fs.writeFile(jsPath, jsContent)]);
  const stats = await fs.stat(jsPath);
  console.log(`Written to ${jsPath} (${(stats.size / 1024 / 1024).toFixed(2)} MB)`);
}

async function fileExists(filepath: string): Promise<boolean> {
  try {
    await fs.access(filepath);
    return true;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  const forceUpdate = process.argv.includes('--force');

  // Check if all generated files exist
  const forwardExists = await fileExists(OUTPUT_PATH);
  const reverseExists = await fileExists(REVERSE_OUTPUT_PATH);
  const enJsonExists = await fileExists(EN_JSON_PATH);

  // Skip if all dictionaries already exist (unless --force)
  if (!forceUpdate && forwardExists && reverseExists && enJsonExists) {
    console.log('Dictionaries already exist, skipping download (use --force to re-download)');
    return;
  }

  let dict: CMUDictionary;
  const text = await downloadDictionary();
  dict = parseDictionary(text);

  const wordCount = Object.keys(dict).length;
  console.log(`Total entries: ${wordCount}`);

  await writeDualOutput(
    OUTPUT_PATH,
    dict,
    'cmudict',
    'Auto-generated CMU dictionary - do not edit'
  );

  // Generate word-frequencies.ts from npm package
  await generateWordFrequencies();

  // Generate reverse dictionary (phoneme key -> words, sorted by frequency)
  await generateReverseDictionary(dict);

  // Generate en.json for the website (CMU dict + custom words merged)
  await generateEnJson(dict);
}

async function generateWordFrequencies(): Promise<void> {
  // Skip if already exists (unless --force)
  const forceUpdate = process.argv.includes('--force');
  if (!forceUpdate && (await fileExists(WORD_FREQ_OUTPUT_PATH))) {
    console.log('Word frequencies already exists, skipping (use --force to regenerate)');
    return;
  }

  // Ensure data directory exists
  await fs.mkdir(path.dirname(WORD_FREQ_OUTPUT_PATH), { recursive: true });

  // Convert array to object: { word: count }
  const frequencyMap: Record<string, number> = {};
  for (const { word, count } of wordFrequencies) {
    frequencyMap[word] = count;
  }

  await writeDualOutput(
    WORD_FREQ_OUTPUT_PATH,
    frequencyMap,
    'WORD_FREQUENCIES',
    'Auto-generated word frequencies - do not edit'
  );
  console.log(`Total words: ${Object.keys(frequencyMap).length}`);
}

/**
 * Strips stress markers (0, 1, 2) from the end of a phoneme.
 */
export function stripStress(phoneme: string): string {
  const lastChar = phoneme.charCodeAt(phoneme.length - 1);
  // '0' = 48, '1' = 49, '2' = 50
  if (lastChar >= 48 && lastChar <= 50) {
    return phoneme.slice(0, -1);
  }
  return phoneme;
}

/**
 * Build word frequency map for sorting.
 */
function buildFrequencyMap(): Map<string, number> {
  const freqMap = new Map<string, number>();
  for (const { word, count } of wordFrequencies) {
    freqMap.set(word.toLowerCase(), count);
  }
  return freqMap;
}

/**
 * Score a word for sorting (higher = more common, should come first).
 * Delegates to the shared runtime scorer in src/frequency.ts so the
 * pre-built reverse dictionary and runtime re-sorts can't drift apart.
 */
export function getWordScore(word: string, freqMap: Map<string, number>): number {
  const freq = freqMap.get(word.toLowerCase());
  return -scoreWordWithFrequency(word, freq !== undefined && freq > 0 ? freq : undefined);
}

/**
 * Generates the reverse dictionary: phoneme key -> words (sorted by frequency).
 */
async function generateReverseDictionary(dict: CMUDictionary): Promise<void> {
  console.log('Generating reverse dictionary...');

  const freqMap = buildFrequencyMap();

  // Build reverse mapping: phoneme key -> words
  const reverseDict: Record<string, string[]> = {};

  for (const [word, phonemes] of Object.entries(dict)) {
    // Strip stress markers and join to create key
    const phonemeKey = phonemes.map(stripStress).join(' ');

    if (!reverseDict[phonemeKey]) {
      reverseDict[phonemeKey] = [];
    }
    reverseDict[phonemeKey].push(word);
  }

  // Sort each word list by score (highest first = most common)
  for (const key of Object.keys(reverseDict)) {
    reverseDict[key].sort((a, b) => {
      return getWordScore(b, freqMap) - getWordScore(a, freqMap);
    });
  }

  const keyCount = Object.keys(reverseDict).length;
  console.log(`Reverse dictionary: ${keyCount} phoneme keys`);

  await writeDualOutput(
    REVERSE_OUTPUT_PATH,
    reverseDict,
    'reverseCmudict',
    'Auto-generated reverse CMU dictionary - do not edit'
  );
}

/**
 * Generates en.json for the website: CMU dict + custom words merged.
 * Custom pronunciations override CMU entries.
 */
async function generateEnJson(dict: CMUDictionary): Promise<void> {
  console.log('Generating en.json (CMU + custom words merged)...');
  const merged = { ...dict };
  let overrides = 0;
  let additions = 0;
  for (const [word, phonemes] of Object.entries(CUSTOM_PRONUNCIATIONS)) {
    if (word in merged) {
      overrides++;
    } else {
      additions++;
    }
    merged[word] = phonemes;
  }
  const json = JSON.stringify(merged);
  await fs.mkdir(path.dirname(EN_JSON_PATH), { recursive: true });
  await fs.writeFile(EN_JSON_PATH, json, 'utf8');
  console.log(
    `  en.json: ${Object.keys(merged).length} entries (${overrides} overrides, ${additions} additions), ${(json.length / 1024 / 1024).toFixed(1)} MB`
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(console.error);
}
