/**
 * NRL/Elovitz letter-to-sound rules for grapheme-to-phoneme conversion.
 *
 * Based on: Elovitz, H., Johnson, R., McHugh, A., and Shore, J. (1976)
 * "Automatic translation of English text to phonetics by means of
 * letter-to-sound rules." NRL Report 7948.
 *
 * 329 context-sensitive rules that examine left and right letter context
 * to determine pronunciation. Each rule has the form:
 *
 *   leftContext[TARGET]rightContext=/PHONEMES/
 *
 * Special context symbols:
 *   #  = 1+ vowels (AEIOUY)
 *   .  = voiced consonant (BDVGJLMNRWZ)
 *   %  = suffix (ER, E, ES, ED, ING, ELY)
 *   &  = sibilant (S, C, G, Z, X, J, CH, SH)
 *   @  = non-palate consonant (T, S, R, D, L, Z, N, J, TH, CH, SH)
 *   ^  = single consonant
 *   +  = front vowel (E, I, Y)
 *   :  = 0+ consonants
 *   ' '= word boundary (space)
 */

import { arpabetToFormat } from '@ingglish/phonemes';
import { applyStressPrediction } from './stress';
import type { OutputFormat } from '@ingglish/phonemes';

// ---------------------------------------------------------------------------
// NRL rules — grouped by first letter of the target
// ---------------------------------------------------------------------------

const NRL_RULES: Record<string, string[]> = {
  A: [
    ' [AYE] =/AY/',
    ' [APRIL]=/EY P R AH L/',
    ' [ANGER]=/AE NG G ER/',
    ' [ARGUE]=/AA R G Y UW/',
    ' [ALCOHOL]=/AE L K AH HH AA L/',
    ' [AVERAGE]=/AE V ER IH JH/',
    ' [ALLY] =/AE L AY/',
    ' [AMEN] =/EY M EH N/',
    ' [ALAN] =/AE L AH N/',
    ' [ANCIENT]=/EY N CH AH N T/',
    ' [AMOUNT]=/AH M AW N T/',
    ' [ALICE] =/AE L AH S/',
    ' [APPARENTLY]=/AH P EH R AH N T L IY/',
    ' [AWESOME]=/AA S AH M/',
    ' [AWARE]=/AH W EH R/',
    ' [ANGELES]=/AE N JH AH L IH S/',
    ' [AMONG]=/AH M AH NG/',
    ' [AGREED]=/AH G R IY D/',
    ' [AMAZING]=/AH M EY Z IH NG/',
    ' [ATTORNEY]=/AH T ER N IY/',
    ' [ASLEEP]=/AH S L IY P/',
    ' [APART]=/AH P AA R T/',
    ' [ALLOW]=/AH L AW/',
    ' [ARREST]=/ER EH S T/',
    ' [AUNT] =/AE N T/',
    ' [APOLOGIZE]=/AH P AA L AH JH AY Z/',
    ' [APPRECIATE]=/AH P R IY SH IY EY T/',
    ' [AMERICAN]=/AH M EH R AH K AH N/',
    ' [AMERICA]=/AH M EH R AH K AH/',
    ' [AGO] =/AH G OW/',
    ' [ANYONE]=/EH N IY W AH N/',
    ' [ANYBODY]=/EH N IY B AH D IY/',
    ' [AND] =/AH N D/',
    ' [ARE] =/AA R/',
    ' [A]BO=/AH/',
    'F[A]VO=/EY/',
    'TR[A]VE=/AE/',
    'F[A]TH=/AA/',
    '[ASTE] =/EY S T/',
    '[ASE] =/EY S/',
    '[A] =/AX/',
    ' [AR]OU=/ER/',
    ' [AR]EN =/AA R/',
    'EP[AR]AT=/ER/',
    '[AR]#=/EH R/',
    ' [AR]O=/AX R/',
    ' ^[AS]#=/EY S/',
    '[A]WA=/AX/',
    '[AWL]=/AO L/',
    '[AW]FU=/AA/',
    '[AW]=/AO/',
    ' :[ANY]=/EH N IY/',
    '[A]HE=/AH/',
    '[A]^+#=/EY/',
    '#:[ALLY]=/AX L IY/',
    ' [AL]#=/AX L/',
    '[AGAIN]=/AX G EH N/',
    'SS[AG]E=/AH JH/',
    '#:[AG]E=/IH JH/',
    ' :[A]^+ =/EY/',
    '[A]^%=/EY/',
    'M[ARR]IE=/EH R/',
    '[ARR]ES=/ER/',
    '[ARR]IV=/ER/',
    '[ARR]=/AE R/',
    ' :[AR] =/AA R/',
    '[AR] =/ER/',
    'ST[AR]D=/ER/',
    '[AR]=/AA R/',
    '[AIR]=/EH R/',
    '[AIGN]=/EY N/',
    'RT[AI]NL=/AH/',
    '[AI]=/EY/',
    '[AY]=/EY/',
    ' L[AUGH]=/AE F/',
    '[AUGH]=/AO/',
    '[AUER]=/AW ER/',
    '[AU]=/AO/',
    '#:[AL] =/AX L/',
    '#:[ALS] =/AX L Z/',
    '[ALK]=/AO K/',
    '[AL]B=/AE L/',
    '[AL]C=/AE L/',
    'H[ALF]=/AE F/',
    'C[ALF]=/AE F/',
    '[AL]F=/AE L/',
    '[AL]G=/AE L/',
    '[AL]P=/AE L/',
    '[AL]V=/AE L/',
    '[ALM] =/AA M/',
    '[ALM]S =/AA M/',
    ' [AL]LE=/AE L/',
    'SH[AL]L=/AE L/',
    ' [AL]LOT=/AH L/',
    '[AL]^=/AO L/',
    ' :[ABLE]=/EY B AX L/',
    '[ABLE]=/AX B AX L/',
    '[ANG]+=/EY N JH/',
    '#:[ANCE] =/AX N S/',
    '#:[ANTS] =/AX N T S/',
    '#:[ANT] =/AX N T/',
    '[AA]=/AA/',
    '[AE]=/EH/',
    ' [A]NO=/AH/',
    '#:[AS] =/AH Z/',
    'M[A]JO=/EY/',
    'SW[A]LL=/AA/',
    'SW[A]P=/AA/',
    'SQU[A]=/AA/',
    'QU[A]NT=/AA/',
    '[A]=/AE/',
    '#:[AN] =/AX N/',
  ],
  B: [
    ' [BODIES]=/B AA D IY Z/',
    ' [BASEBALL]=/B EY S B AO L/',
    ' [BORROW]=/B AA R OW/',
    ' [BARBARA]=/B AA R B ER AH/',
    ' [BRAVO]=/B R AA V OW/',
    ' [BIBLE]=/B AY B AH L/',
    ' [BLAH]=/B L AA/',
    ' [BURY]=/B EH R IY/',
    ' [BRITISH]=/B R IH T IH SH/',
    ' [BESIDES]=/B IH S AY D Z/',
    ' [BEYOND]=/B IH AA N D/',
    ' [BRIAN]=/B R AY AH N/',
    ' [BURIED]=/B EH R IY D/',
    ' [BRILLIANT]=/B R IH L Y AH N T/',
    ' [BOTHER]=/B AA DH ER/',
    ' [BASTARD]=/B AE S T ER D/',
    ' [BREATHE]=/B R IY DH/',
    ' [BEAUTY]=/B Y UW T IY/',
    ' [BREATH] =/B R EH TH/',
    ' [BREAKFAST]=/B R EH K F AH S T/',
    ' [BEAR]=/B EH R/',
    ' [BOUGHT] =/B AA T/',
    ' [BUSINESS]=/B IH Z N AX S/',
    ' [BETWEEN]=/B IH T W IY N/',
    ' [BOTH] =/B OW TH/',
    ' [BEEN] =/B IH N/',
    ' [BE]^#=/B IH/',
    '[BEING]=/B IY IH NX/',
    ' [BUS]#=/B IH Z/',
    '[BUIL]=/B IH L/',
    '[BT]=/T/',
    '#:[BERG] =/B ER G/',
    '#:[BURG] =/B ER G/',
    '#:[BURY] =/B EH R IY/',
    '[BB]=/B/',
    'M[B] =/ /',
    '[B]=/B/',
  ],
  C: [
    ' [CHRIST] =/K R AY S T/',
    ' [CHOCOLATE]=/CH AO K L AH T/',
    ' [CREATE]=/K R IY EY T/',
    ' [CAROL] =/K AE R AH L/',
    ' [CLIMB]=/K L AY M/',
    ' [CHALLENGE]=/CH AE L AH N JH/',
    ' [CLOWN]=/K L AW N/',
    ' [CHARITY]=/CH EH R IH T IY/',
    ' [CIVIL]=/S IH V AH L/',
    ' [CLINIC]=/K L IH N IH K/',
    ' [CEREMONY]=/S EH R AH M OW N IY/',
    ' [CASINO]=/K AH S IY N OW/',
    ' [CAPABLE]=/K EY P AH B AH L/',
    ' [CATHERINE]=/K AE TH ER AH N/',
    ' [CHLOE]=/K L OW IY/',
    ' [CLEARLY]=/K L IH R L IY/',
    ' [CELEBRATE]=/S EH L AH B R EY T/',
    ' [CIGARETTE]=/S IH G ER EH T/',
    ' [CIGAR]=/S IH G AA R/',
    ' [COS] =/K AO S/',
    ' [CLOSET]=/K L AA Z AH T/',
    ' [CHINA]=/CH AY N AH/',
    ' [CHARLOTTE]=/SH AA R L AH T/',
    ' [COURAGE]=/K ER AH JH/',
    ' [CONFERENCE]=/K AA N F ER AH N S/',
    ' [CHAMPAGNE]=/SH AE M P EY N/',
    ' [CONTRACT]=/K AA N T R AE K T/',
    ' [CROWD]=/K R AW D/',
    ' [CREDIT] =/K R EH D AH T/',
    ' [COMMON]=/K AA M AH N/',
    ' [CLOSER] =/K L OW S ER/',
    ' [CONVERSATION]=/K AA N V ER S EY SH AH N/',
    ' [CONSIDER]=/K AH N S IH D ER/',
    ' [COMFORTABLE]=/K AH M F ER T AH B AH L/',
    ' [CONTACT]=/K AA N T AE K T/',
    ' [COFFEE] =/K AA F IY/',
    ' [CORRECT]=/K ER EH K T/',
    ' [CHARLES]=/CH AA R L Z/',
    ' [COUSIN]=/K AH Z AH N/',
    ' [COST] =/K AA S T/',
    ' [CONTROL]=/K AH N T R OW L/',
    ' [CONGRATULATIONS]=/K AH N G R AE CH AH L EY SH AH N Z/',
    ' [COUNTRY]=/K AH N T R IY/',
    ' [CHINESE]=/CH AY N IY Z/',
    ' [CHOOSE]=/CH UW Z/',
    ' [CHICAGO]=/SH AH K AA G OW/',
    ' [CHARACTER]=/K EH R IH K T ER/',
    ' [CAREER]=/K ER IH R/',
    ' [CAMERA]=/K AE M ER AH/',
    ' [COLONEL]=/K ER N AH L/',
    ' [COLLEGE]=/K AA L IH JH/',
    ' [CLOTHES]=/K L OW DH Z/',
    ' [CLOSE] =/K L OW S/',
    ' [CERTAIN]=/S ER T AH N/',
    ' [CAUSE]=/K AA Z/',
    ' [CAUGHT] =/K AA T/',
    ' [CHRISTMAS]=/K R IH S M AH S/',
    ' [CITY]=/S IH T IY/',
    ' [CAPTAIN]=/K AE P T AX N/',
    ' [CHA]R=/CH AA/',
    ' [CH]^=/K/',
    '^E[CH]=/K/',
    '[CHEM]=/K EH M/',
    'BA[CH] =/K/',
    'TE[CH] =/K/',
    'EI[CH] =/K/',
    'LO[CH] =/K/',
    'RO[CH] =/K/',
    'MA[CH] =/K/',
    'NE[CH] =/K/',
    'NO[CH] =/K/',
    'DO[CH] =/K/',
    'ZE[CH] =/K/',
    'I[CH]T=/K/',
    'I[CH]EL=/K/',
    'I[CH]OL=/K/',
    'A[CH]EN=/K/',
    'A[CH]TE=/K/',
    'R[CH]IV=/K/',
    'R[CH]IT=/K/',
    'S[CH]KE=/K/',
    '[CH]=/CH/',
    ' S[CI]#=/S AY/',
    '[CIAL]=/SH AX L/',
    '[CI]A=/SH/',
    '[CI]O=/SH/',
    '[CI]EN=/SH/',
    'EX[C]IT=//',
    'EX[C]E=//',
    '[C]+=/S/',
    '[CK]=/K/',
    '[CZ]=/CH/',
    '[CQU]=/K W/',
    'I[CALLY] =/K L IY/',
    '[CYCL]=/S AY K AH L/',
    ' [CON]^=/K AH N/',
    '[COM]%=/K AH M/',
    '[CCH]=/K/',
    'M[CC]=/AH K/',
    '[CC]+=/K S/',
    '[CC]=/K/',
    'M[C]^=/AH K/',
    '[C]=/K/',
  ],
  D: [
    ' [DIRECT]=/D ER EH K T/',
    ' [DESTINY]=/D EH S T AH N IY/',
    ' [DALLAS]=/D AE L AH S/',
    ' [DESSERT]=/D IH Z ER T/',
    ' [DIAMOND]=/D AY M AH N D/',
    ' [DEGREE]=/D IH G R IY/',
    ' [DENY]=/D IH N AY/',
    ' [DELIVER]=/D IH L IH V ER/',
    ' [DATA]=/D EY T AH/',
    ' [DECENT] =/D IY S AH N T/',
    ' [DESERT]=/D EH Z ER T/',
    ' [DANIEL]=/D AE N Y AH L/',
    ' [DOZEN]=/D AH Z AH N/',
    ' [DEMON]=/D IY M AH N/',
    ' [DIRECTOR]=/D ER EH K T ER/',
    ' [DOLLARS]=/D AA L ER Z/',
    ' [DEFINITELY]=/D EH F AH N AH T L IY/',
    ' [DIFFICULT]=/D IH F AH K AH L T/',
    ' [DEVIL]=/D EH V AH L/',
    ' [DAVID]=/D EY V IH D/',
    ' [DONE] =/D AH N/',
    ' [DOING]=/D UW IH NX/',
    ' [DOES] =/D AH Z/',
    '#:[DED] =/D IH D/',
    '.E[D] =/D/',
    '#TE[D] =/IH D/',
    '#^:E[D] =/T/',
    '[DIAG]=/D AY AH G/',
    '[DIAL]=/D AY AH L/',
    ' [DE]^#=/D IH/',
    '[DU]A=/JH UW/',
    '[DG]+=/JH/',
    '[DJ]=/JH/',
    '#:[DDED] =/D IH D/',
    '[DD]=/D/',
    '[D]T =/ /',
    '[D]=/D/',
  ],
  E: [
    ' [EQUAL]=/IY K W AH L/',
    ' [EXIT]=/EH G Z IH T/',
    ' [EVENT]=/IH V EH N T/',
    ' [EFFORT]=/EH F ER T/',
    ' [EDUCATION]=/EH JH AH K EY SH AH N/',
    ' [EMILY]=/EH M IH L IY/',
    ' [ELEVATOR]=/EH L AH V EY T ER/',
    ' [ELIZABETH]=/IH L IH Z AH B AH TH/',
    ' [EXPERT]=/EH K S P ER T/',
    ' [EXTREMELY]=/EH K S T R IY M L IY/',
    ' [ESTATE]=/IH S T EY T/',
    ' [ENGLAND]=/IH NG G L AH N D/',
    ' [ENGINE]=/EH N JH AH N/',
    ' [EVE] =/IY V/',
    ' [EUROPE]=/Y UH R AH P/',
    ' [EAR] =/IY R/',
    ' [ESCAPE]=/IH S K EY P/',
    ' [EXCEPT]=/IH K S EH P T/',
    ' [ESPECIALLY]=/AH S P EH SH L IY/',
    ' [EXCELLENT]=/EH K S AH L AH N T/',
    ' [EMERGENCY]=/IH M ER JH AH N S IY/',
    ' [ENEMY]=/EH N AH M IY/',
    ' [EXCUSE]=/IH K S K Y UW S/',
    ' [EVIL]=/IY V AH L/',
    ' [ENTIRE]=/IH N T AY ER/',
    ' [ENGLISH]=/IH NG G L IH SH/',
    ' [EVERYONE]=/EH V R IY W AH N/',
    ' [EVERY]^=/EH V R IY/',
    ' [EITHER]=/IY DH ER/',
    ' [EVEN] =/IY V IH N/',
    ' [EVE]N=/IY V/',
    ' [E]LE=/IH/',
    ' [E]NO=/IH/',
    ' [EX]#=/IH G Z/',
    '#:[E] =/ /',
    ' :[E] =/IY/',
    '#[ED] =/D/',
    'D[ED] =/IH D/',
    '#:[E]D =/ /',
    '[EV]ER=/EH V/',
    '[ER]%=/ER/',
    '#:[EMENT]=/M AX N T/',
    '#:[ENED] =/AX N D/',
    '#:[ENING]=/AX N IH NX/',
    '#:[ENESS] =/N AX S/',
    '#:[EMAN] =/M AX N/',
    '[ERR]=/EH R/',
    'XP[ER]IE=/IH R/',
    '#:[ER]#=/ER/',
    'S[ER]IO=/IH R/',
    '[ER]#=/EH R/',
    '[ER]=/ER/',
    '@[EW]=/UW/',
    '#:[E]W=/ /',
    '[EW]=/Y UW/',
    'G[E]OR=//',
    '[E]O=/IY/',
    'IC[ES] =/AH Z/',
    '#:&[ES] =/IH Z/',
    '#:[E]S =/ /',
    '#:[ELY] =/L IY/',
    '#:[EFUL] =/F AX L/',
    '[EFUL]=/F UH L/',
    '[EER]=/IH R/',
    '[EE]=/IY/',
    '[EARN]=/ER N/',
    '[EAR]TH=/ER/',
    '[EAR]L=/ER/',
    '[EAR]CH=/ER/',
    '[EAR]T=/ER/',
    '[EAR] =/IH R/',
    '[EAR]S =/IH R/',
    '[EAD]=/EH D/',
    '#:[EA] =/IY AX/',
    '[EAUX]=/OW/',
    'B[EAU]TI=/Y UW/',
    '[EAU]=/OW/',
    '[EA]SU=/EH/',
    'D[EA]TH=/EH/',
    'BR[EA]K=/EY/',
    'W[EA]PO=/EH/',
    '[EA]=/IY/',
    '[EIGH]=/EY/',
    'C[EI]=/IY/',
    'W[EI]RD=/IH/',
    '[EI]=/AY/',
    '[EU]RO=/Y UW/',
    '[EY]E=/AY/',
    '[EY]=/IY/',
    '[EUR] =/ER/',
    '[EU]=/UW/',
    '#:[ENCE] =/AX N S/',
    '#:[ENTS] =/AX N T S/',
    '#:[ENT] =/AX N T/',
    'I[ELD]=/L D/',
    'I[ELS] =/L Z/',
    'I[EL] =/L/',
    '#:[ENS] =/AX N Z/',
    '#:[EN] =/AX N/',
    'OT[EL]=/EH L/',
    '#:[EL] =/AX L/',
    '#:[EST] =/AX S T/',
    '[EX]TR=/EH K S/',
    ' [EX]^=/IH K S/',
    '#:[ELS] =/AX L Z/',
    '#:[ETS] =/AH T S/',
    '#:[EMS] =/AX M Z/',
    '#:[EM] =/AX M/',
    '#:[ET] =/AH T/',
    'P[E]TE=/IY/',
    'D[E]FE=/IH/',
    'D[E]FI=/IH/',
    'R[E]CE=/IH/',
    'D[E]CI=/IH/',
    'R[E]SP=/IH/',
    'R[E]PR=/IY/',
    'S[E]CR=/IY/',
    'S[E]CU=/IH/',
    'R[E]TR=/IY/',
    'D[E]PR=/IH/',
    'D[E]STR=/IH/',
    'D[E]PL=/IH/',
    'D[E]CL=/IH/',
    'D[E]PE=/IH/',
    'D[E]SI=/IH/',
    'D[E]TE=/IH/',
    'R[E]SU=/IH/',
    'R[E]GA=/IH/',
    '[E]VOL=/IH/',
    'CK[E]TT=/IH/',
    'NN[E]LL=/AH/',
    'SS[E]LL=/AH/',
    'DD[E]LL=/AH/',
    'PP[E]LL=/AH/',
    'RR[E]LL=/AH/',
    'TT[E]LL=/AH/',
    'NK[E]TT=/IH/',
    'FF[E]LL=/AH/',
    'LL[E]TT=/IH/',
    'RR[E]TT=/IH/',
    'MM[E]LL=/AH/',
    'NN[E]TT=/IH/',
    'NN[E]SS=/IH/',
    'MM[E]TT=/IH/',
    'GG[E]TT=/IH/',
    'LL[E]NG=/IH/',
    'TL[E]ME=//',
    'B[E]TW=/IH/',
    'PR[E]TT=/IH/',
    'PR[E]TE=/IY/',
    'PR[E]PA=/IY/',
    'PR[E]VE=/IY/',
    'PR[E]CA=/IY/',
    'PR[E]MI=/IY/',
    'PR[E]SC=/IY/',
    'PR[E]VI=/IY/',
    'CR[E]TE=/IY/',
    'PL[E]TE=/IY/',
    'TL[E]ME=//',
    'ST[E]VE=/IY/',
    ' [E]QU=/IH/',
    ' [E]FF=/IH/',
    ' [E]MI=/IH/',
    'D[E]SC=/IH/',
    'EL[E]BR=/AH/',
    'EL[E]PH=/AH/',
    '[E]NB=/AH/',
    '[E]NSTE=/AH/',
    '[E]=/EH/',
  ],
  F: [
    ' [FEVER]=/F IY V ER/',
    ' [FASHION]=/F AE SH AH N/',
    ' [FLORIDA]=/F L AO R AH D AH/',
    ' [FOCUS]=/F OW K AH S/',
    ' [FORTUNE]=/F AO R CH AH N/',
    ' [FRASIER]=/F R EY ZH ER/',
    ' [FOREIGN]=/F AO R AH N/',
    ' [FEMALE]=/F IY M EY L/',
    ' [FINDING]=/F AY N D IH NG/',
    ' [FALLING]=/F AA L IH NG/',
    ' [FELLAS]=/F EH L AH S/',
    ' [FOOT]=/F UH T/',
    ' [FLOWER]=/F L AW ER/',
    ' [FRIDAY]=/F R AY D IY/',
    ' [FAMOUS]=/F EY M AH S/',
    ' [FIGURE]=/F IH G Y ER/',
    ' [FIRE]=/F AY ER/',
    ' [FOREVER]=/F ER EH V ER/',
    ' [FORGET]=/F ER G EH T/',
    ' [FORGIVE]=/F ER G IH V/',
    ' [FORGOT]=/F ER G AA T/',
    ' [FAVORITE]=/F EY V ER IH T/',
    ' [FINISH]=/F IH N IH SH/',
    ' [FROM]=/F R AH M/',
    '#:[FORD] =/F ER D/',
    '#:[FULLY] =/F AX L IY/',
    '#:[FUL] =/F AX L/',
    '[FUL]=/F UH L/',
    '[FF]=/F/',
    '[F]=/F/',
  ],
  G: [
    ' [GIMME]=/G IH M IY/',
    ' [GIANT]=/JH AY AH N T/',
    ' [GUITAR]=/G IH T AA R/',
    ' [GROSS]=/G R OW S/',
    ' [GEAR]=/G IH R/',
    ' [GARAGE]=/G ER AA ZH/',
    ' [GENIUS]=/JH IY N Y AH S/',
    ' [GRANDPA] =/G R AE N D P AA/',
    ' [GHOST]=/G OW S T/',
    ' [GRANDMA]=/G R AE N D M AA/',
    ' [GOVERNMENT]=/G AH V ER M AH N T/',
    ' [GROWN]=/G R OW N/',
    ' [GORGEOUS]=/G AO R JH AH S/',
    ' [GAS] =/G AE S/',
    ' [GUEST]=/G EH S T/',
    ' [GENTLEMEN]=/JH EH N T AH L M IH N/',
    ' [GN]=/N/',
    '[G]EI=/G/',
    ' [GONE] =/G AO N/',
    '[GIV]=/G IH V/',
    ' [G]I^=/G/',
    '[GEON]=/JH AX N/',
    '[GE]T=/G EH/',
    'SU[GGES]=/G JH EH S/',
    '[GU]I=/G/',
    '[GG]=/G/',
    ' B#[G]=/G/',
    'ER[G]ER=/G/',
    '[G]ERN=/G/',
    '[G]+=/JH/',
    '[GREAT]=/G R EY T/',
    '#[GH]=/ /',
    '[G]=/G/',
  ],
  H: [
    ' [HEADACHE]=/HH EH D EY K/',
    ' [HARVARD]=/HH AA R V ER D/',
    ' [HALLOWEEN]=/HH AE L AH W IY N/',
    ' [HAROLD]=/HH EH R AH L D/',
    ' [HOLMES]=/HH OW M Z/',
    ' [HERCULES]=/HH ER K Y AH L IY Z/',
    ' [HIRE]=/HH AY ER/',
    ' [HONOUR]=/AA N ER/',
    ' [HOLLYWOOD]=/HH AA L IY W UH D/',
    ' [HANGING]=/HH AE NG IH NG/',
    ' [HMM]=/HH M/',
    ' [HANDSOME]=/HH AE N S AH M/',
    ' [HUNDRED]=/HH AH N D R AH D/',
    ' [HONEY]=/HH AH N IY/',
    ' [HOLY]=/HH OW L IY/',
    ' [HEAVEN]=/HH EH V AH N/',
    ' [HEAVY]=/HH EH V IY/',
    ' [HERO]=/HH IH R OW/',
    ' [HEALTH]=/HH EH L TH/',
    ' [HARRY]=/HH EH R IY/',
    ' [HUSBAND]=/HH AH Z B AX N D/',
    ' [HONEST]=/AA N AH S T/',
    ' [HONOR]=/AA N ER/',
    ' [HOUR]=/AW ER/',
    ' [HEART]=/HH AA R T/',
    ' [HEARD] =/HH ER D/',
    ' [HELLO]=/HH AH L OW/',
    ' [HEAR] =/HH IY R/',
    ' [HEY] =/HH EY/',
    ' [HAVEN]=/HH EY V AH N/',
    ' [HAVE]=/HH AE V/',
    ' [HERE] =/HH IY R/',
    ' [HER] =/HH ER/',
    ' [HIM] =/HH IH M/',
    ' [HIS] =/HH IH Z/',
    '[HOW]=/HH AW/',
    '[H]#=/HH/',
    '[H]=/ /',
  ],
  I: [
    ' [ILLEGAL]=/IH L IY G AH L/',
    ' [INSURANCE]=/IH N SH UH R AH N S/',
    ' [IDEAS]=/AY D IY AH Z/',
    ' [IMMEDIATELY]=/IH M IY D IY AH T L IY/',
    ' [INFORMATION]=/IH N F ER M EY SH AH N/',
    ' [INTERESTED]=/IH N T R AH S T IH D/',
    ' [INNOCENT]=/IH N AH S AH N T/',
    ' [IDIOT]=/IH D IY AH T/',
    ' [ISLAND]=/AY L AH N D/',
    ' [INTEREST]=/IH N T R AH S T/',
    'CH[ILD]RE=/IH L D/',
    'LL[I]ON=/Y/',
    'M[I]CR=/AY/',
    'WH[I]TE=/AY/',
    '[I]DEA=/AY/',
    ' [INTO] =/IH N T UW/',
    '[INI] =/IY N IY/',
    '[INO] =/IY N OW/',
    '[INA] =/IY N AH/',
    '[ISA] =/IY S AH/',
    '[IVA] =/IY V AH/',
    '[IMA] =/IY M AH/',
    '[ITO] =/IY T OW/',
    '[ITA] =/IY T AH/',
    '#:[IALLY]=/IY AX L IY/',
    '#:[IAL]=/IY AX L/',
    '#:[IATE]=/IY EY T/',
    '[INDS] =/AY N D Z/',
    '[IN]D =/AY N/',
    '#:R[IED] =/IY D/',
    '[IED] =/AY D/',
    'FR[IEN]=/EH N/',
    '[IE]F=/IY/',
    '[IE]G=/IY/',
    '[IE]V=/IY/',
    '[IE]C=/IY/',
    '[IE]W=/IY/',
    '[IE]P=/IY/',
    '[IE]B=/IY/',
    '[IE]L=/IY/',
    '[IE]^%=/IY/',
    ' :[I]%=/AY/',
    'QU[I]ET=/AY/',
    '[I]%=/IY/',
    '[IE]=/IY/',
    '[IAN] =/IY AX N/',
    '[IUM] =/IY AX M/',
    '[IA] =/IY AX/',
    '[IO] =/IY OW/',
    '[IFY]=/AX F AY/',
    '[ITY] =/AX T IY/',
    '[IBLE]=/AX B AX L/',
    '[IOUS]=/IY AX S/',
    ' [I]DE=/AY/',
    'L[I]KE=/AY/',
    'W[I]DE=/AY/',
    'W[I]SE=/AY/',
    'T[I]RE=/AY/',
    'R[I]PE=/AY/',
    'PR[I]CE=/AY/',
    'SP[I]TE=/AY/',
    'FF[I]CU=/AH/',
    'SP[IR]IT=/IH R/',
    '[I]^EM=/AY/',
    'OT[I]CE=/AH/',
    'RV[I]CE=/AH/',
    'EV[I]DE=/AH/',
    'CT[I]CE=/AH/',
    'ACR[I]F=/AH/',
    'LT[I]PL=/AH/',
    'DR[I]VE=/AY/',
    'GU[I]LD=/IH/',
    'UN[I]VE=/AH/',
    '[I]^+:#=/IH/',
    '[IRR]=/ER/',
    '[IR]#=/AY R/',
    '[IZ]%=/AY Z/',
    'ES[I]DE=/AH/',
    '[I]D%=/AY/',
    '[I]T%=/AY/',
    'T[I]VE=/IH/',
    'S[I]VE=/IH/',
    'AL[I]VE=/AY/',
    'L[I]VI=/IH/',
    'AM[I]LY=/AH/',
    'FF[I]CER=/AH/',
    'OM[I]NI=/AH/',
    'PRES[I]DE=/AH/',
    'UT[I]FU=/AH/',
    '[I]^+=/AY/',
    '[IR]=/ER/',
    '[IGH]=/AY/',
    '[ILD]=/AY L D/',
    '[IGN] =/AY N/',
    '[IGN]^=/AY N/',
    '[IGN]%=/AY N/',
    '[IQUE]=/IY K/',
    '^[I] =/IY/',
    '#:[ISMS] =/IH Z AX M Z/',
    '#:[ISM] =/IH Z AX M/',
    'RM[I]NA=/AH/',
    'IM[I]NA=/AH/',
    'OM[I]NA=/AH/',
    'EM[I]NA=/AH/',
    'ED[I]CA=/AH/',
    'UN[I]CA=/AH/',
    'AM[I]NA=/AH/',
    'UM[I]NA=/AH/',
    'OL[I]DA=/AH/',
    'AN[I]MA=/AH/',
    'IN[I]ST=/AH/',
    'NT[I]MA=/AH/',
    'IC[I]PA=/AH/',
    'EC[I]FI=/AH/',
    'IL[I]TA=/AH/',
    'IM[I]TA=/AH/',
    'IG[I]TA=/AH/',
    'ON[I]TO=/AH/',
    'F[I]NA=/AY/',
    'ST[I]GA=/AH/',
    '[I]BLY=/AH/',
    '[I]=/IH/',
  ],
  J: [
    ' [JONATHAN]=/JH AA N AH TH AH N/',
    ' [JOURNEY]=/JH ER N IY/',
    ' [JOSEPH]=/JH OW S AH F/',
    ' [JESSE] =/JH EH S IY/',
    ' [JUICE]=/JH UW S/',
    ' [JUNIOR]=/JH UW N Y ER/',
    ' [JUSTICE]=/JH AH S T AH S/',
    ' [JEALOUS]=/JH EH L AH S/',
    ' [JESUS]=/JH IY Z AH S/',
    '[J]=/JH/',
  ],
  K: [' [KNOWLEDGE]=/N AA L AH JH/', ' [K]N=/ /', '[KK]=/K/', '[K]=/K/'],
  L: [
    ' [LINCOLN]=/L IH NG K AH N/',
    ' [LION]=/L AY AH N/',
    ' [LAS] =/L AA S/',
    ' [LOSS] =/L AO S/',
    ' [LOUIS] =/L UW IH S/',
    ' [LEATHER]=/L EH DH ER/',
    ' [LIMIT]=/L IH M AH T/',
    ' [LOUISE]=/L UW IY Z/',
    ' [LILY]=/L IH L IY/',
    ' [LICENSE]=/L AY S AH N S/',
    ' [LIAR]=/L AY ER/',
    ' [LEGAL]=/L IY G AH L/',
    ' [LIBRARY]=/L AY B R EH R IY/',
    ' [LOUSY]=/L AW Z IY/',
    ' [LANGUAGE]=/L AE NG G W AH JH/',
    ' [LOSING]=/L UW Z IH NG/',
    ' [LIEUTENANT]=/L UW T EH N AH N T/',
    ' [LEAD] =/L EH D/',
    ' [LONDON]=/L AH N D AH N/',
    ' [LAWYER]=/L AO Y ER/',
    ' [LARRY]=/L EH R IY/',
    ' [LOSE]=/L UW Z/',
    ' [LOST] =/L AO S T/',
    '[LO]C#=/L OW/',
    'L[L]=/ /',
    '#:[LINE] =/L AY N/',
    '#:[LESSLY] =/L AX S L IY/',
    'UN[LESS]=/L EH S/',
    '#:[LESS] =/L AX S/',
    '[LING]=/L IH NX/',
    '#^:[L]ER=/L/',
    '#^:[L]EY=/L/',
    '[LEAD]=/L IY D/',
    'OB[L]EM=/L/',
    '#^:[L]ET=/L/',
    '#^:[L]%=/AX L/',
    '[LDT] =/L T/',
    '[LL]=/L/',
    'EA[L]IZ=/AH L/',
    '[L]=/L/',
  ],
  M: [
    ' [MARINE]=/M ER IY N/',
    ' [MISSILE]=/M IH S AH L/',
    ' [MUSEUM]=/M Y UW Z IY AH M/',
    ' [MATTHEW]=/M AE TH Y UW/',
    ' [MARIE] =/M ER IY/',
    ' [MARGARET]=/M AA R G ER IH T/',
    ' [MEDICINE]=/M EH D AH S AH N/',
    ' [MEDIA]=/M IY D IY AH/',
    ' [MIRROR]=/M IH R ER/',
    ' [MIRACLE]=/M IH R AH K AH L/',
    ' [MOSTLY]=/M OW S T L IY/',
    ' [MOOD]=/M UW D/',
    ' [MONKEY]=/M AH NG K IY/',
    ' [MONDAY]=/M AH N D IY/',
    ' [MAGAZINE]=/M AE G AH Z IY N/',
    ' [MADAME]=/M AE D AH M/',
    ' [MONSIEUR]=/M AH S Y ER/',
    ' [MEXICO]=/M EH K S AH K OW/',
    ' [MOUNTAIN]=/M AW N T AH N/',
    ' [MAJESTY]=/M AE JH AH S T IY/',
    ' [MARTIN] =/M AA R T AH N/',
    ' [MANAGER]=/M AE N AH JH ER/',
    ' [MESSAGE]=/M EH S AH JH/',
    ' [MACHINE]=/M AH SH IY N/',
    ' [MAYBE]=/M EY B IY/',
    ' [MICHAEL]=/M AY K AH L/',
    ' [MARRIAGE]=/M EH R IH JH/',
    ' [MAMA]=/M AA M AH/',
    ' [MEANT] =/M EH N T/',
    ' [MARRY]=/M EH R IY/',
    ' [MRS]=/M IH S IH Z/',
    ' [MARRIED]=/M EH R IY D/',
    ' [MINUTE]=/M IH N AH T/',
    '[MOV]=/M UW V/',
    '[MBS] =/M Z/',
    '[MB] =/M/',
    '[MN]ING=/M/',
    '[MN]ED=/M/',
    '[MN]S=/M/',
    '[MN] =/M/',
    '#:[MENTS] =/M AX N T S/',
    '#:[MENT] =/M AX N T/',
    '#:[MAN] =/M AX N/',
    '#:[MEN] =/M AX N/',
    '[MM]=/M/',
    '[M]=/M/',
  ],
  N: [
    ' [NUCLEAR]=/N UW K L IY ER/',
    ' [NEPHEW]=/N EH F Y UW/',
    ' [NOEL]=/N OW EH L/',
    ' [NEARLY]=/N IH R L IY/',
    ' [NAH] =/N AA/',
    ' [NATIONAL]=/N AE SH AH N AH L/',
    ' [NEIGHBORHOOD]=/N EY B ER HH UH D/',
    ' [NEEDED]=/N IY D AH D/',
    ' [NECESSARY]=/N EH S AH S EH R IY/',
    ' [NAKED]=/N EY K AH D/',
    ' [NATURE]=/N EY CH ER/',
    ' [NOWHERE]=/N OW W EH R/',
    ' [NEITHER]=/N IY DH ER/',
    ' [NOW]=/N AW/',
    'E[NG]+=/N JH/',
    '[NG]ING=/NX/',
    '[NG]ED=/NX/',
    'LI[NG]ER=/NX/',
    'NI[NG]ER=/NX/',
    'DI[NG]ER=/NX/',
    'RI[NG]ER=/NX/',
    'SI[NG]ER=/NX/',
    'TI[NG]ER=/NX/',
    'ZI[NG]ER=/NX/',
    'MI[NG]ER=/NX/',
    'BI[NG]ER=/NX/',
    '[NG]R=/NX G/',
    '[NG]#=/NX G/',
    '[NGL]%=/NX G AX L/',
    '[NG]=/NX/',
    '[NKC]=/NX K/',
    '[NK]=/NX K/',
    '#:[NESS] =/N AX S/',
    '[NDT] =/N T/',
    '[NN]=/N/',
    '[N]=/N/',
  ],
  O: [
    ' [OPPOSITE]=/AA P AH Z AH T/',
    ' [ORANGE]=/AO R AH N JH/',
    ' [OCEAN]=/OW SH AH N/',
    ' [OPINION]=/AH P IH N Y AH N/',
    ' [OPPORTUNITY]=/AA P ER T UW N AH T IY/',
    ' [ONTO] =/AA N T UW/',
    ' [OFFICE] =/AO F IH S/',
    ' [OFTEN]=/AO F AH N/',
    ' [OUTTA]=/UW T AH/',
    ' [ONES] =/W AH N Z/',
    ' [O]CC=/AH/',
    ' [O]PP=/AH/',
    ' [ONCE] =/W AH N S/',
    ' [ONLY]=/OW N L IY/',
    ' [ONE] =/W AH N/',
    ' [OUR]=/AW ER/',
    '[OROUGH]=/ER OW/',
    '#:[ORY] =/ER IY/',
    '#:[OR] =/ER/',
    '#:[ORS] =/ER Z/',
    '[ORR]=/AO R/',
    '[OR]=/AO R/',
    'T[OWN]=/AW N/',
    'D[OWN]=/AW N/',
    'R[OWN]=/AW N/',
    'G[OWN]=/AW N/',
    'P[OW]=/AW/',
    'C[OW]=/AW/',
    'V[OW]=/AW/',
    'F[OW]L=/AW/',
    'FL[OW]ER=/AW/',
    'T[OW]ER=/AW/',
    '[OW]=/OW/',
    'I[ONED] =/AX N D/',
    'I[ONING]=/AX N IH NX/',
    'I[ONER]=/AX N ER/',
    'I[ONERS]=/AX N ER Z/',
    'C[O]MP=/AH/',
    'C[O]MM=/AH/',
    'C[O]LL=/AH/',
    'M[O]N%=/AH/',
    'L[O]V=/AH/',
    'N[O]TH=/AH/',
    'T[O]GE=/AH/',
    'W[O]ND=/AH/',
    'PR[O]VE=/UW/',
    'C[O]MF=/AH/',
    'C[O]VE=/AH/',
    'PR[O]TE=/AH/',
    'PR[O]VI=/AH/',
    'PR[O]PO=/AH/',
    'PR[O]FE=/AH/',
    'PR[O]DU=/AH/',
    'PR[O]NO=/AH/',
    'G[O]VE=/AH/',
    'P[O]LI=/AH/',
    'SH[O]VE=/AH/',
    'AB[O]VE=/AH/',
    'M[O]DE=/AA/',
    ' [O]BS=/AH/',
    'D[O]G=/AO/',
    'N[O]MI=/AA/',
    ' [O]PEN=/OW/',
    ' [O]PE=/AA/',
    'M[O]NTH=/AH/',
    'N[O]NE=/AH/',
    'PR[O]PE=/AA/',
    'IS[O]NE=/AH/',
    'S[O]NE=/AH/',
    'PR[O]CE=/AH/',
    '[O]^%=/OW/',
    '[O]^EN=/OW/',
    '[O]^I#=/OW/',
    '[OLK]=/OW K/',
    '[OL]T=/OW L/',
    '[OL]D=/OW L/',
    '[OL]Z=/OW L/',
    '[OL]S=/OW L/',
    '[OL]B=/OW L/',
    '[OL]M=/OW L/',
    '[OL]N=/OW L/',
    '[OL]P=/OW L/',
    '[OUGHT]=/AO T/',
    'D[OUGH]=/OW/',
    'B[OUGH] =/AW/',
    'C[OUGH]=/AA F/',
    'T[OUGH] =/AH F/',
    'R[OUGH] =/AH F/',
    'N[OUGH] =/AH F/',
    '[OUGH] =/AW/',
    '[OUGH]=/AH F/',
    '[OUSE]=/AW S/',
    'H[OU]S#=/AW/',
    '[OUS]=/AX S/',
    '#:[OUR] =/ER/',
    '[OUR]=/AO R/',
    'W[OULD] =/UH D/',
    'C[OULD] =/UH D/',
    'SH[OULD] =/UH D/',
    '[OULD]=/OW L D/',
    '^[OU]^L=/AH/',
    '[OUP]=/UW P/',
    'T[OU]CH=/AH/',
    'Y[OU]NG=/AH/',
    '[OU]=/AW/',
    '[OY]=/OY/',
    '[OING]=/OW IH NX/',
    '[OI]=/OY/',
    '[OOR]=/AO R/',
    '[OOSE]=/UW S/',
    '[OOK]=/UH K/',
    'BL[OOD]=/AH D/',
    'F[OOD]=/UW D/',
    'FL[OOD]=/AH D/',
    '[OOD]=/UH D/',
    '[OO]=/UW/',
    '[OE]=/OW/',
    '#:[OH] =/OW/',
    '[O] =/OW/',
    '[OAR]=/AO R/',
    '[OA]=/OW/',
    '[O]NG=/AO/',
    'I[ON]=/AX N/',
    '#:[ON] =/AX N/',
    '#^[ON]=/AX N/',
    '[OSIS]=/OW S IH S/',
    '[O]ST =/OW/',
    '[O]S =/OW/',
    '[OFF]=/AO F/',
    '[OTHER]=/AH DH ER/',
    '#^:[OM]=/AH M/',
    '[OLOGY]=/AA L AH JH IY/',
    'T[O]DA=/AH/',
    'W[O]MA=/UH/',
    '[O]^A=/OW/',
    'C[O]LO=/AH/',
    '[O]^O=/OW/',
    '[O]BI=/OW/',
    '[O]TI=/OW/',
    '[O]SI=/OW/',
    '[O]GL=/OW/',
    '[O]FI=/OW/',
    '[O]KI=/OW/',
    'P[O]ST=/OW/',
    'CR[O]SS=/AO/',
    'FR[O]NT=/AH/',
    '#:[ONS] =/AH N Z/',
    '#:[OL] =/AO L/',
    'D[O]ZEN=/AH/',
    'TR[O]DU=/AH/',
    'M[O]NK=/AH/',
    'W[O]MAN=/UH/',
    'M[O]NGO=/AA/',
    'W[O]LF=/UH/',
    '[O]=/AA/',
    '#:[OT] =/AH T/',
  ],
  P: [
    ' [PENIS]=/P IY N IH S/',
    ' [PRIVACY]=/P R AY V AH S IY/',
    ' [PRAYER]=/P R EH R/',
    ' [PATROL]=/P AH T R OW L/',
    ' [PALACE]=/P AE L AH S/',
    ' [PIERCE]=/P IH R S/',
    ' [PREFER] =/P R AH F ER/',
    ' [PLEASANT]=/P L EH Z AH N T/',
    ' [PITY]=/P IH T IY/',
    ' [PIZZA]=/P IY T S AH/',
    ' [PILOT]=/P AY L AH T/',
    ' [PRIEST]=/P R IY S T/',
    ' [PROCESS]=/P R AA S EH S/',
    ' [PERIOD]=/P IH R IY AH D/',
    ' [POLICY]=/P AA L AH S IY/',
    ' [PERCENT]=/P ER S EH N T/',
    ' [POSITIVE]=/P AA Z AH T IH V/',
    ' [PURPOSE]=/P ER P AH S/',
    ' [PROJECT]=/P R AA JH EH K T/',
    ' [PERFECTLY]=/P ER F AH K T L IY/',
    ' [PLANET]=/P L AE N AH T/',
    ' [PROGRAM]=/P R OW G R AE M/',
    ' [PROBABLY]=/P R AA B AH B L IY/',
    ' [PHOEBE]=/F IY B IY/',
    ' [PAPA]=/P AA P AH/',
    ' [PRESIDENT]=/P R EH Z AH D EH N T/',
    ' [PRIVATE]=/P R AY V AH T/',
    ' [POOR]=/P UW R/',
    ' [POSITION]=/P AH Z IH SH AH N/',
    ' [PERSONAL]=/P ER S AH N AH L/',
    ' [POLICE]=/P AH L IY S/',
    ' [PROMISE]=/P R AA M AH S/',
    ' [PN]=/N/',
    '[PH]=/F/',
    '[PEOP]=/P IY P/',
    '[POW]=/P AW/',
    '[PUT] =/P UH T/',
    '[PP]=/P/',
    '[P]=/P/',
  ],
  Q: ['[QUAR]=/K W AO R/', '[QUA]L=/K W AA/', '[QUE] =/K/', '[QU]=/K W/', '[Q]=/K/'],
  R: [
    ' [RUSSIAN]=/R AH SH AH N/',
    ' [RECOGNIZE]=/R EH K AH G N AY Z/',
    ' [REPEAT]=/R IH P IY T/',
    ' [ROUTINE]=/R UW T IY N/',
    ' [RUTH] =/R UW TH/',
    ' [REVEREND]=/R EH V ER AH N D/',
    ' [REALITY]=/R IY AE L AH T IY/',
    ' [ROUTE]=/R UW T/',
    ' [RESPONSIBILITY]=/R IY S P AA N S AH B IH L AH T IY/',
    ' [ROBIN]=/R AA B AH N/',
    ' [REGRET]=/R AH G R EH T/',
    ' [REGULAR]=/R EH G Y AH L ER/',
    ' [RESPONSIBLE]=/R IY S P AA N S AH B AH L/',
    ' [READING]=/R IY D IH NG/',
    ' [RELEASE]=/R IY L IY S/',
    ' [RADAR]=/R EY D AA R/',
    ' [RESTAURANT]=/R EH S T ER AA N T/',
    ' [RELAX]=/R IH L AE K S/',
    ' [ROBERT]=/R AA B ER T/',
    ' [ROGER]=/R AA JH ER/',
    ' [RIVER]=/R IH V ER/',
    ' [RECORD]=/R AH K AO R D/',
    ' [RICHARD]=/R IH CH ER D/',
    ' [REALIZE]=/R IY AH L AY Z/',
    ' [REALLY]=/R IH L IY/',
    ' [RE]ME=/R IH/',
    ' [RE]SP=/R IH/',
    ' [RE]QU=/R IH/',
    ' [RE]MA=/R IH/',
    ' [RE]TU=/R IH/',
    ' [RE]FU=/R IH/',
    ' [RE]GA=/R IH/',
    ' [RE]VE=/R IH/',
    ' [RE]^#=/R IY/',
    '[ROLL]=/R OW L/',
    '[RH]=/R/',
    '[RDT] =/R T/',
    '[RR]=/R/',
    '[R]=/R/',
  ],
  S: [
    ' [SACRED]=/S EY K R AH D/',
    ' [SPECIES]=/S P IY SH IY Z/',
    ' [STEPHEN]=/S T IY V AH N/',
    ' [SCHEDULE]=/S K EH JH UH L/',
    ' [SECRETARY]=/S EH K R AH T EH R IY/',
    ' [SEXUAL]=/S EH K SH UW AH L/',
    ' [SUPPLY]=/S AH P L AY/',
    ' [SERIES]=/S IH R IY Z/',
    ' [SURVEILLANCE]=/S ER V EY L AH N S/',
    ' [STEAK]=/S T EY K/',
    ' [SATELLITE]=/S AE T AH L AY T/',
    ' [STANDARD]=/S T AE N D ER D/',
    ' [SHOE]=/SH UW/',
    ' [SWORD]=/S AO R D/',
    ' [SENIOR]=/S IY N Y ER/',
    ' [SWEAT]=/S W EH T/',
    ' [SILENCE]=/S AY L AH N S/',
    ' [SIMON] =/S AY M AH N/',
    ' [SALLY]=/S AE L IY/',
    ' [SQUARE]=/S K W EH R/',
    ' [SOCIETY]=/S AH S AY AH T IY/',
    ' [STOMACH]=/S T AH M AH K/',
    ' [SAFETY]=/S EY F T IY/',
    ' [SUGAR]=/SH UH G ER/',
    ' [SUGGEST]=/S AH JH EH S T/',
    ' [SUDDENLY]=/S AH D AH N L IY/',
    ' [STRENGTH] =/S T R EH NG K TH/',
    ' [STUDY]=/S T AH D IY/',
    ' [SEVERAL]=/S EH V R AH L/',
    ' [SHERIFF]=/SH EH R AH F/',
    ' [SHOWER]=/SH AW ER/',
    ' [SOLDIER]=/S OW L JH ER/',
    ' [SATURDAY]=/S AE T ER D IY/',
    ' [SWEETHEART]=/S W IY T HH AA R T/',
    ' [STEVE]=/S T IY V/',
    ' [STUPID]=/S T UW P AH D/',
    ' [SERGEANT]=/S AA R JH AH N T/',
    ' [SOUL]=/S OW L/',
    ' [SCENE]=/S IY N/',
    ' [SHOES]=/SH UW Z/',
    ' [SWEAR]=/S W EH R/',
    ' [SOMEONE]=/S AH M W AH N/',
    ' [SERIOUS]=/S IH R IY AH S/',
    ' [SECRET]=/S IY K R AH T/',
    ' [SAYS] =/S EH Z/',
    ' [SORRY]=/S AA R IY/',
    ' [SON] =/S AH N/',
    ' [SURE]=/SH UH R/',
    '[SH]=/SH/',
    '#[SION]=/ZH AX N/',
    '#:[SIDE] =/S AY D/',
    '[SCH]OO=/S K/',
    '[SOME]=/S AH M/',
    '#[SUR]#=/ZH ER/',
    '[SUR]#=/SH ER/',
    '#[SU]#=/ZH UW/',
    '#[SSU]#=/SH UW/',
    '#[SED] =/Z D/',
    '[S]IVE=/S/',
    'IU[S] =/S/',
    ' RE[S]#=/S/',
    ' DI[S]I=/S/',
    ' DI[S]O=/S/',
    ' DI[S]AR=/S/',
    ' DI[S]T=/S/',
    ' DI[S]AG=/S/',
    ' DI[S]EM=/S/',
    ' DI[S]AP=/S/',
    ' DI[S]AF=/S/',
    'MY[S]EL=/S/',
    '#[S]#=/Z/',
    '[SAID]=/S EH D/',
    '^[SION]=/SH AX N/',
    '[S]S=/ /',
    'SE[S] =/AH Z/',
    'GE[S] =/AH Z/',
    '.[S] =/Z/',
    '#:.E[S] =/Z/',
    '#^:##[S] =/Z/',
    'A[S] =/Z/',
    'O[S] =/Z/',
    '#^:#[S] =/S/',
    'U[S] =/S/',
    ' :#[S] =/Z/',
    'AN[SWER]=/S ER/',
    '[SCH]=/SH/',
    '[S]C+=/ /',
    '[STLE]=/S AX L/',
    '#:[STEN]=/S AX N/',
    '#:[STEIN] =/S T AY N/',
    '#:[SON] =/S AX N/',
    '[SS]=/S/',
    '[S]=/S/',
  ],
  T: [
    ' [THEORY]=/TH IH R IY/',
    ' [THEE] =/DH IY/',
    ' [TOWEL]=/T AW AH L/',
    ' [THEME]=/TH IY M/',
    ' [TOKYO]=/T OW K IY OW/',
    ' [TRAGEDY]=/T R AE JH AH D IY/',
    ' [THROWN]=/TH R OW N/',
    ' [TITLE]=/T AY T AH L/',
    ' [THERAPY]=/TH EH R AH P IY/',
    ' [TIGER]=/T AY G ER/',
    ' [TELEVISION]=/T EH L AH V IH ZH AH N/',
    ' [TEAR] =/T EH R/',
    ' [THEATER]=/TH IY AH T ER/',
    ' [THREAT]=/TH R EH T/',
    ' [THY] =/DH AY/',
    ' [THOU] =/DH AW/',
    ' [TALENT]=/T AE L AH N T/',
    ' [TUESDAY]=/T UW Z D IY/',
    ' [TOWARD]=/T AH W AO R D/',
    ' [TAXI]=/T AE K S IY/',
    ' [TOWARDS]=/T AH W AO R D Z/',
    ' [THOMAS]=/T AA M AH S/',
    ' [TONGUE]=/T AH NG/',
    ' [TELEPHONE]=/T EH L AH F OW N/',
    ' [TOUR]=/T UH R/',
    ' [TARGET]=/T AA R G AH T/',
    ' [TERRIFIC]=/T ER IH F IH K/',
    ' [THEMSELVES]=/DH EH M S EH L V Z/',
    ' [TRIAL]=/T R AY AH L/',
    ' [TONY]=/T OW N IY/',
    ' [TIRED]=/T AY ER D/',
    ' [TONIGHT]=/T AH N AY T/',
    ' [TOMORROW]=/T AH M AA R OW/',
    ' [THE] =/DH AX/',
    ' [THIS] =/DH IH S/',
    ' [THEY]=/DH EY/',
    ' [THERE]=/DH EH R/',
    ' [THEN]=/DH EH N/',
    ' [THAN] =/DH AE N/',
    ' [THEM] =/DH EH M/',
    ' [TWO]=/T UW/',
    '[THAT] =/DH AE T/',
    '[THER]=/DH ER/',
    '[THEIR]=/DH EH R/',
    '[THESE] =/DH IY Z/',
    '[THROUGH]=/TH R UW/',
    '[THOSE]=/DH OW Z/',
    '[THOUGH] =/DH OW/',
    '[TH]=/TH/',
    '#:[TED] =/T IH D/',
    'S[TI]#N=/CH/',
    '[TI]O=/SH/',
    '[TIAL]=/SH AX L/',
    '[TI]A=/SH/',
    '[TIEN]=/SH AX N/',
    '[TUR]#=/CH ER/',
    '[TU]A=/CH UW/',
    '[TZ]=/T S/',
    '[TSCH]=/CH/',
    '#:[TOWN] =/T AW N/',
    '#:[TIME] =/T AY M/',
    '[TCH]=/CH/',
    '#:[TTED] =/T IH D/',
    '[TT]=/T/',
    '[T]=/T/',
  ],
  U: [
    ' [UNIFORM]=/Y UW N AH F AO R M/',
    ' [UNFORTUNATELY]=/AH N F AO R CH AH N AH T L IY/',
    ' [UNIT] =/Y UW N AH T/',
    ' [UPSET]=/AH P S EH T/',
    ' [UPON]=/AH P AA N/',
    ' [USE] =/Y UW S/',
    ' [UNCLE]=/AH NG K AH L/',
    ' [UNLESS]=/AH N L EH S/',
    'IN[U]TE=/AH/',
    'TR[U]TH=/UW/',
    'P[U]LL=/UH/',
    'B[U]LL=/UH/',
    'P[U]SH=/UH/',
    ' [UN]IN=/AH N/',
    ' [UN]I=/Y UW N/',
    ' [UN]#=/AH N/',
    ' [UN]^=/AH N/',
    '[UIT]=/UW T/',
    '[URR]=/ER/',
    '@[UR]#=/UH R/',
    '[UR]#=/Y UH R/',
    '[UR]=/ER/',
    '[U]^ =/AH/',
    'C[U]SH=/UH/',
    'B[U]SH=/UH/',
    '[U]^^=/AH/',
    '[UY]=/AY/',
    ' G[U]#=/ /',
    'G[U]%=/ /',
    'G[U]#=/W/',
    '#N[U]=/Y UW/',
    '[ULAT]=/Y AX L EY T/',
    '[ULOUS]=/Y AX L AH S/',
    '[ULUS]=/Y AX L AH S/',
    '[ULAR]=/Y AX L ER/',
    'ST[U]DY=/AH/',
    '@[U]=/UW/',
    '[U] =/UW/',
    '[U]=/Y UW/',
  ],
  V: [
    ' [VIETNAM]=/V IY EH T N AA M/',
    ' [VALENTINE]=/V AE L AH N T AY N/',
    ' [VEHICLE]=/V IY HH IH K AH L/',
    ' [VALLEY]=/V AE L IY/',
    ' [VACATION]=/V EY K EY SH AH N/',
    ' [VICTIM]=/V IH K T AH M/',
    ' [VEGAS]=/V EY G AH S/',
    ' [VISIT]=/V IH Z IH T/',
    '[VIEW]=/V Y UW/',
    '[VIOL]=/V AY AH L/',
    '[V]=/V/',
  ],
  W: [
    ' [WHEREVER]=/W EH R EH V ER/',
    ' [WHORE]=/HH AO R/',
    ' [WHOO]=/W UW/',
    ' [WIRE]=/W AY ER/',
    ' [WEATHER]=/W EH DH ER/',
    ' [WILLIAM]=/W IH L Y AH M/',
    ' [WORRIED]=/W ER IY D/',
    ' [WITHIN]=/W IH DH IH N/',
    ' [WEAPON]=/W EH P AH N/',
    ' [WASTE]=/W EY S T/',
    ' [WEIRD]=/W IH R D/',
    ' [WEAR]=/W EH R/',
    ' [WICKED]=/W IH K AH D/',
    ' [WOUNDED]=/W UW N D IH D/',
    ' [WANTED]=/W AO N T IH D/',
    ' [WHOA]=/W OW/',
    ' [WOMEN]=/W IH M AH N/',
    ' [WATER]=/W AO T ER/',
    ' [WORRY]=/W ER IY/',
    ' [WON] =/W AH N/',
    ' [WITH] =/W IH DH/',
    '[WA]STE=/W EY/',
    '[WA]S=/W AA/',
    '[WA]T=/W AA/',
    '[WA]N=/W AA/',
    '[WA]M=/W AA/',
    '[WHERE]=/WH EH R/',
    '[WHAT]=/WH AH T/',
    '[WHOL]=/HH OW L/',
    '[WHO]=/HH UW/',
    '[WH]=/WH/',
    '#:[WARDS] =/W ER D Z/',
    '#:[WARD] =/W ER D/',
    '[WAR]=/W AO R/',
    '[WOR]^=/W ER/',
    ' [WOW]=/W AW/',
    '[WR]=/R/',
    '[W]=/W/',
  ],
  X: ['[X]=/K S/'],
  Y: [
    ' [YOURSELVES]=/Y UH R S EH L V Z/',
    ' [YOURS] =/Y UH R Z/',
    ' [YET] =/Y EH T/',
    ' [YES] =/Y EH S/',
    'H[Y]DR=/AY/',
    'H[Y]PE=/AY/',
    '#^:[Y] =/IY/',
    '#^:[Y]I=/IY/',
    ' :[Y] =/AY/',
    ' [YOURSELF]=/Y ER S EH L F/',
    ' [YOU] =/Y UW/',
    ' [YOUR]=/Y AO R/',
    ' [YEAH]=/Y AE/',
    ' [Y]#=/Y/',
    ' :[Y]#=/AY/',
    ' :[Y]^+:#=/IH/',
    ' :[Y]^#=/AY/',
    '[Y] =/IY/',
    'AW[Y]ER=/Y/',
    'DB[Y]E=/AY/',
    '[Y]=/IH/',
  ],
  Z: ['[ZZ]=/Z/', '[Z]=/Z/'],
};

// ---------------------------------------------------------------------------
// Character class expansions (NRL special symbols → regex fragments)
// ---------------------------------------------------------------------------

const VOWELS = 'AEIOUY';
const CONSONANTS = 'BCDFGHJKLMNPQRSTVWXZ';

const CLASSES: Record<string, string> = {
  '#': `[${VOWELS}]+`,
  '.': '[BDVGJLMNRWZ]',
  '%': '(?:ER|E|ES|ED|ING|ELY)',
  '&': '(?:S|C|G|Z|X|J|CH|SH)',
  '@': '(?:T|S|R|D|L|Z|N|J|TH|CH|SH)',
  '^': `[${CONSONANTS}]`,
  '+': '[EIY]',
  ':': `[${CONSONANTS}]*`,
};

const SPECIAL_CHARS = new Set(Object.keys(CLASSES));

// ---------------------------------------------------------------------------
// NRL phoneme → ARPAbet mapping
// ---------------------------------------------------------------------------

// NRL vowels get stress markers. AX (schwa) → AH0, others → stress 1.
const NRL_VOWELS = new Set([
  'AA',
  'AE',
  'AH',
  'AO',
  'AW',
  'AY',
  'EH',
  'ER',
  'EY',
  'IH',
  'IY',
  'OW',
  'OY',
  'UH',
  'UW',
]);

function nrlToArpabet(phoneme: string): string {
  if (phoneme === 'AX') {
    return 'AH0';
  }
  if (phoneme === 'NX') {
    return 'NG';
  }
  if (phoneme === 'WH') {
    return 'W';
  }
  if (NRL_VOWELS.has(phoneme)) {
    return phoneme + '1';
  }
  return phoneme;
}

// ---------------------------------------------------------------------------
// Compiled rule structure
// ---------------------------------------------------------------------------

interface CompiledRule {
  leftRe: RegExp;
  rightRe: RegExp;
  targetLen: number;
  phonemes: string[]; // ARPAbet phonemes (empty array for silence)
  ruleStr: string; // Original NRL rule string
}

export interface G2PTraceStep {
  letters: string; // Target letters consumed (e.g., "ASE")
  rule: string; // Original NRL rule string (e.g., "[ASE] =/EY S/")
  phonemes: string[]; // ARPAbet output after stress (e.g., ["EY1", "S"])
}

export interface G2PTrace {
  phonemes: string[]; // Final ARPAbet (after stress prediction)
  steps: G2PTraceStep[]; // Rules that fired, in order
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Expand NRL context symbols into regex fragments. */
function expandContext(ctx: string): string {
  let result = '';
  for (const ch of ctx) {
    if (SPECIAL_CHARS.has(ch)) {
      result += CLASSES[ch]!;
    } else {
      result += escapeRegex(ch);
    }
  }
  return result;
}

/** Parse a single NRL rule string into a compiled rule. */
function compileRule(ruleStr: string): CompiledRule | null {
  // Format: leftContext[TARGET]rightContext=/PHONEMES/
  const m = /^([^[]*)\[([^\]]+)\]([^=]*)=\/(.*)\/$/.exec(ruleStr);
  if (m === null) {
    return null;
  }

  const leftCtx = m[1]!;
  const target = m[2]!;
  const rightCtx = m[3]!;
  const phonemeStr = m[4]!;

  // Build left regex (anchored at end of parsed text)
  const leftPattern = expandContext(leftCtx);
  const leftRe = new RegExp(leftPattern + '$');

  // Build right regex (anchored at start: target literal + expanded context)
  const rightPattern = expandContext(rightCtx);
  const rightRe = new RegExp('^' + escapeRegex(target) + rightPattern);

  // Parse phonemes: strip delimiters, split, map to ARPAbet
  const phonemes = phonemeStr
    .trim()
    .split(/\s+/)
    .filter((p) => p.length > 0)
    .map(nrlToArpabet);

  return { leftRe, rightRe, targetLen: target.length, phonemes, ruleStr };
}

// ---------------------------------------------------------------------------
// Compile all rules at module load time
// ---------------------------------------------------------------------------

const COMPILED_RULES: Record<string, CompiledRule[]> = {};

for (const [letter, rules] of Object.entries(NRL_RULES)) {
  const compiled: CompiledRule[] = [];
  for (const rule of rules) {
    const c = compileRule(rule);
    if (c !== null) {
      compiled.push(c);
    }
  }
  COMPILED_RULES[letter] = compiled;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Converts a word to ARPAbet using NRL context-sensitive rules,
 * returning both the phonemes and a trace of which rules fired.
 */
export function wordToArpabetTraced(word: string): G2PTrace {
  // Pad with spaces for word-boundary matching
  const text = ' ' + word.toUpperCase() + ' ';
  const rawPhonemes: string[] = [];
  const rawSteps: { letters: string; ruleStr: string; count: number }[] = [];
  let pos = 1; // skip leading space

  while (pos < text.length - 1) {
    // trailing space is a boundary, not a character to process
    const parsed = text.substring(0, pos);
    const rest = text.substring(pos);
    const ch = text[pos]!;

    // Look up rules for this letter
    const rules = COMPILED_RULES[ch] as CompiledRule[] | undefined;
    if (rules !== undefined) {
      let matched = false;
      for (const rule of rules) {
        if (rule.leftRe.test(parsed) && rule.rightRe.test(rest)) {
          rawPhonemes.push(...rule.phonemes);
          rawSteps.push({
            letters: text.substring(pos, pos + rule.targetLen),
            ruleStr: rule.ruleStr,
            count: rule.phonemes.length,
          });
          pos += rule.targetLen;
          matched = true;
          break;
        }
      }
      if (!matched) {
        pos++; // skip unrecognized character
      }
    } else {
      pos++; // skip non-letter characters
    }
  }

  const phonemes = applyStressPrediction(word, rawPhonemes);

  // Map post-stress phonemes back to each step
  const steps: G2PTraceStep[] = [];
  let offset = 0;
  for (const raw of rawSteps) {
    steps.push({
      letters: raw.letters,
      rule: raw.ruleStr,
      phonemes: phonemes.slice(offset, offset + raw.count),
    });
    offset += raw.count;
  }

  return { phonemes, steps };
}

/**
 * Converts a word to ARPAbet using NRL context-sensitive rules.
 *
 * @param word The word to convert
 * @returns Array of ARPAbet phonemes
 */
export function wordToArpabet(word: string): string[] {
  return wordToArpabetTraced(word).phonemes;
}

/**
 * Translates an unknown word using NRL letter-to-sound rules.
 * This is a fallback when the word isn't in the dictionary.
 *
 * @param word The unknown word
 * @param format The output format
 * @returns The best-effort translation
 */
export function translateWithRules(word: string, format: OutputFormat = 'ingglish'): string {
  const arpabet = wordToArpabet(word);
  return arpabetToFormat(arpabet, format);
}
